### ISSUE TITLE
Read–eval–print loop

### ISSUE THREAD

**Issue by jamesrdf** [IbcAlpha/IBC#104]
I'm interested in creating a shell to control TWS/Gateway. I plan on exposing the TWS-API through stdout/stdin, encoding objects in JSON. Commands from stdin would get mapped to EClient method calls and calls to EWrapper method would get mapped to stdout. My main goal would be to allow orders, data, and monitoring via nodejs or other shell script. Startup/shutdown would utilize IbcAlpha (of course), but the shell would allow any TWS-API command to be sent.

Would this be something of interest to IbcAlpha contributors? Should I follow up with a PR here? Any more ideas/suggestions before I get started next month?

**Comment by rlktradewright** [comment]
I see no reason at all why what you want to do should affect IBC in any way.

What you are talking about should be an entirely separate project. By all means use IBC to start TWS/Gateway, but don't expect the IBC software to participate in any way other than that.

IBC's only function is to start, stop and manage some aspects of running TWS/Gateway that would otherwise require manual intervention.

I should point out that you don't have to run IBC as the main entrypoint in a process: you can use it as a library from within a process running other software (provided that software has the ability to load Java classes, and that should encompass any language that runs on or interoperates with the Java virtual machine). This would result in TWS/Gateway running within the same process as your software: whether that is a good idea is debatable, but it does work.

There is a sample of IBC being used in this way at https://github.com/IbcAlpha/IBC/tree/master/samples/IbcLoader.

And of course you can always run IBC just by executing a script from your application.

If you decide to run IBC as a library, then improvements to the mechanisms that permit this would certainly be candidates for PRs, but please discuss first. An example would be providing the ability to inject a logging mechanism so that IBC's logging would be integrated with that of the calling application (this is mentioned in the description of the sample above).

**Comment by jamesrdf** [comment]
Thanks for your prompt feedback. IBC is a great bit of software and makes sense to keep it focused. Any further discussion about controlling IB TWS via client API can be redirected to here: https://github.com/jamesrdf/tws-shell
