### ISSUE TITLE
Java(TM) Platform SE binary stop working  Issue

### ISSUE THREAD

**Issue by memoryfraction** [IbcAlpha/IBC#11]
Some times, I met "Java(TM) Platform SE binary stop working " error. And TWS stop working , then communication failed too. This happens every 1-3 days.
![image](https://user-images.githubusercontent.com/18358791/40879957-e3e61c3e-6676-11e8-8da0-7a8da0886667.png)

log is attached at that day.
Can Update JRE fix this issue?
[IBC-3.6.0_TWS-963_THURSDAY.zip](https://github.com/IbcAlpha/IBC/files/2065285/IBC-3.6.0_TWS-963_THURSDAY.zip)

**Comment by rlktradewright** [comment]
The log file shows that you want IBC to shut down TWS at 16:20 on Thursday, so presumably you have 

`ClosedownAt=Thursday 16:20`

in your config.ini (with Thursday expressed in the Unicode equivalent for the Chinese characters).

But when 16:20 is reached, there are the following log entries:

>2018-05-31 16:20:00:556 IBC: Getting main window
>2018-05-31 16:20:00:764 IBC: Creating main window future

What's happening here is that IBC is trying to initiate the tidy shutdown, but it's unable to do anything on the UI thread: the only reason I know of for this is that you have a modal dialog on display, for example from `Help > About Trader Workstation...`  Modal dialogs like this prevent access to the menu entries, so IBC is unable to do the tidy shutdown.

To avoid this issue, make sure you don't have any such modal dialog showing at shutdown time. 

A similar problem occurs if you are running TWS with a non-English language setting, eg Simplified Chinese: if you do this, all the menu entries are also in Chinese, and IBC is unable to locate the required menu items, since it only 'speaks' English. I realise that might be unsatisfactory for those whose preferred language is not English, but there simply isn't the effort available to internationalise IBC so that it works with every language version of TWS.

Note that it's only TWS that you have to run in English: you can set your operating system language to anything you like.

**Comment by memoryfraction** [comment]
Appreciate your help. 
First, TWS is running in English now.
Second, about your assumption, I guess it's below dialog blocks the tidy shut down;

![image](https://user-images.githubusercontent.com/18358791/40882848-a34eca0e-66bc-11e8-92ef-f5ced70cc2ae.png)

Next , I am going to fix above issue and see what happens next;

**Comment by memoryfraction** [comment]
I followed below link, step A and B to solve above issue. 
https://ibkr.info/node/2155

72 hours past, TWS is working good without block;
I think I can say, problem solved; 
Really appreciate your help!!!
