### ISSUE TITLE
TWS 981>985: "Error initializing QuantumRenderer: no suitable pipeline found"

### ISSUE THREAD

**Issue by ValeryNo** [IbcAlpha/IBC#132]
Hi! Will really appreciate any suggestions with this.

Upgraded from TWS 981>985 and using latest IBCAlpha 3.8.7 (previously 3.8.4 beta 2).
Getting this error - "Error initializing QuantumRenderer: no suitable pipeline found"

I normally provide my jts.ini but excluded for now to simplify troubleshooting.

Full log file attached.

[ibc-3.8.7_GATEWAY-985_Saturday.txt](https://github.com/IbcAlpha/IBC/files/7025979/ibc-3.8.7_GATEWAY-985_Saturday.txt)

**Comment by rlktradewright** [comment]
My guess here is that your Java runtime at `/opt/i4j_jres/1.8.0_152-tzdata2019c/bin` is not up-to-date and is missing some javafx components.

Since that is not the 'standard' location for the Java runtime after a TWS install, you must have copied the runtime files there yourself at some point in the past. I suspect that when you installed 985, you didn't copy again the runtime files from where the installer puts them into this folder? Although 985 uses the same runtime version as 981, it probably uses additional javafx runtime features that weren't included in the earlier TWS builds, and so aren't in your runtime folder.

So make sure this folder includes all the runtime files installed with 985.

I might be completely wrong about all this, but it seems like a plausible explanation for what's happening...

**Comment by ValeryNo** [comment]
Thank you for suggestions. 

The explanation makes sense (JRE without JavaFX components), but this is the exact JRE installed by official up-to-date TWS script. In this particular case I have recreated the whole linux environment from scratch so there was no JRE there or any old versions and one installed came from current - https://download2.interactivebrokers.com/installers/tws/latest-standalone/tws-latest-standalone-linux-x64.sh

When I look at this jre directory I see jfxswt.jar, javafx.properties and a JavaFX related license file. So it's somewhat aware of JavaFX. But that certainly doesn't prove some implementation / module jar is not missing. 

Any other ideas on what I can check? 

Here is exactly how that setup is done if that helps:
```
FROM ubuntu:18.04

RUN  apt-get update \
  && apt-get install -y wget \
  && apt-get install -y netcat \
  && apt-get install -y unzip \
  && apt-get install -y xvfb \
  && apt-get install -y libxtst6 \
  && apt-get install -y libxrender1 \
  && apt-get install -y libxi6 \
    && apt-get install -y x11vnc \
  && apt-get install -y socat \
  && apt-get install -y software-properties-common \
  && apt-get install -y dos2unix

# Setup IB TWS
RUN mkdir -p /opt/TWS
WORKDIR /opt/TWS
RUN wget -q https://download2.interactivebrokers.com/installers/ibgateway/latest-standalone/ibgateway-latest-standalone-linux-x64.sh
RUN chmod a+x ibgateway-latest-standalone-linux-x64.sh

...
```

**Comment by ValeryNo** [comment]
Ok.. Figured it out. And really sorry for waisting your time!

So that exception in the title of this issue can be ignored. For purists, installing one extra package will help to get rid of it
`sudo apt-get install openjfx`

The real problem was me. Somehow I messed up my VNC configuration I used to connect to this container. Normally if it doesn't connect - something went wrong and I look at logs. Which is why I ended up thinking this error is a problem (the only exception). The container actually ended up starting just fine.

All good, closing this issue.
