### ISSUE TITLE
IBC won't start - Can't find the TWS entry point

### ISSUE THREAD

**Issue by Swarmix23** [IbcAlpha/IBC#145]
Hello,
My IBC has started showing an error and won't start.
One day the login went fine and the next day, without making any changes, it started displaying an error:

IBC: Can't find the TWS entry point: jclient.LoginFrame.main; TWS is not correctly installed.

TWS version 981
IBC version 3.10.0

Can you please help me?
Thank you very much.

**Comment by yezhengli-Mr9** [comment]
Beginner (hopefully developer) try to convert `ant build` into `maven` #33
```java
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /<repo_path>/src/main/java/ibcalpha/ibc/IbcTws.java:[438,22] package ibgateway does not exist
[ERROR] /<repo_path>/src/main/java/ibcalpha/ibc/IbcTws.java:[471,20] package jclient does not exist
[INFO] 2 errors 
[INFO] -----------------------------------
```
Ubuntu 20.04, 22.04.

**Comment by rlktradewright** [comment]
@yezhengli-Mr9 

Your comment has nothing to do with this issue. You should have opened a new issue. Also I notice you've submitted three posts for moderation to the IBC User Group that appear to be on the same subject. This is bad form. 

When you need help, think clearly about the problem you are having, ask ONE question at the place you think is most likely to be able to hel;p, and then wait patiently for a response. Don't blast your question all over the place - that just annoys people.

Anyway, the answer to your question is that packages ibgateway and jclient are within TWS itself, so you have to include a reference to the TWS jar files in your compilation project. You'll find them at C:\Jts\nnnn\jars where nnnn is the TWS version. It doesn't really matter which version of TWS you reference, because these packages haven't changed their signatures for many many years. So you don't need to rebuild every time there's a new TWS version.
