### ISSUE TITLE
"Re-Login" dialog not automated

### ISSUE THREAD

**Issue by rsgabriel** [IbcAlpha/IBC#15]
I've started using IBC. (v3.6.0) for a little over a week and have faced this issue twice in that time. 

My client will indicate the gateway is down, however when I remote into the gateway server I see it is stuck at this prompt.  

I will capture a screenshot the next time this issue occurs. 

Is this a known issue? I see there are no newer releases than the one I have.

Is there any data I can capture or tools I can use to obtain information about the dialog to expedite this ticket? Would using Inspect (https://msdn.microsoft.com/en-us/library/windows/desktop/dd318521(v=vs.85).aspx) be of any use?

**Comment by rlktradewright** [comment]
As far as I'm aware, the only time the gateway displays this prompt is when another session with the same login is started somewhere.

Note that this happens quite often when using the demo system, but I presume you're not using that?

To guard against this scenario, you can set `ExistingSessionDetectedAction=primary` in your config.ini file (but don't do this if you are using the demo system).

If you aren't using the demo system, and you're sure you're not inadvertently logging in with the same username and password elsewhere, then set `LogComponents=activate` in config.ini. Next time the offending dialog is displayed, details of its structure will be recorded in the IBC log file, and you can then attach the log file here for me to look at.

**Comment by rsgabriel** [comment]
By demo system, do you mean, "paper trading"? In which case, I am.

>but don't do this if you are using the demo system

What is the reason to not do this on the demo system?

>If you aren't using the demo system, and you're sure you're not inadvertently logging in with the same username and password elsewhere ...

Can we do this anyway to smooth testing using the paper trading system?

**Comment by rlktradewright** [comment]
The demo system is the one that has username=edemo and password=demouser. It is a system available to everyone - no need to have a funded account. It uses simulated, not real, market data, and there are limitations in its functionality. It's intended primarily to allow non-IBKR account holders to have a play with the TWS/Gateway software, presumably to help them decide whether to sign up with IBKR. In other words, it's primarily a marketing tool, though many developers use it for initial development and limited out-of-hours testing.

When you login to the demo system, you are allocated one of a number of shared demo accounts at random. If it happens that this account is already logged in by someone else, then the existing session detection mechanism comes into place. If one of the users is using IBC and has  `ExistingSessionDetectedAction=primary`, then their session will continue. But if both use IBC and both have this setting, then the two sessions will continually steal control, and neither will get anywhere: that's why you're not advised to use this setting on the demo account.

Paper trading accounts are much more realistic, but require that you have a funded account with IBKR.

If you want to be able to use your paper trading or live account from two or more TWS/Gateway instances simultaneously, then you need to have request additional logins (via Account Management): note that each additional login will have to pay market data fees.

Note also that if you run your live account and your paper trading account at the same time, they must be running on the same (physical or virtual) machine, otherwise you will only get market data on one of them (this limitation is a result of IBKR's licensing agreements with the market data providers). I think this doesn't apply to professional market data subscribers.

**Comment by rsgabriel** [comment]
I have successfully reproduced the issue with the logs enabled.

Log here: https://pastebin.com/XLNMwABb

**Comment by rlktradewright** [comment]
I've managed to produce an identical log to yours, and the problem is indeed that something else, somewhere, is logging in to the same paper trading account. 

Note that it need not be another instance of the gateway: it could be TWS, or perhaps even the mobile trading app (I've never used that and don't have an Android or IoS phone to try it, but I suspect that anything at all that logs in with the same credentials will cause this problem). Note in particular that it needn't be in the same machine.

I suggest you set `ExistingSessionDetectedAction=primary` for your gateway, and then try to discover what it is that's logging in, and then prevent that from happening.

If you're using Task Scheduler to start the gateway, make sure it's not accidentally starting additional instance(s) while the first one is running. It's absolutely vital that you use the /INLINE parameter in the task's action definition. This is because as far as Task Scheduler is concerned, the task is just the command window that processes the StartGateway command, not the actual IBC process. So once that command window exits, Task Scheduler thinks the task is finished even if the IBC process is still running. Using /INLINE prevents this happening.

**Comment by rsgabriel** [comment]
I am using Task Scheduler to start IBC, but I was not using the /INLINE command line parameter. I have corrected this and restarted my instance.

That said, I do have the ClosedownAt set in my config.iniand the task itself is set to run only once a week on Sunday. And this issue occurred on a Tuesday in the morning

Barring a bad actor, there are no other instances of IB gateway or TWS running anywhere on any system using our account. This is the only machine where I have installed IB Gateway.

If I set ExistingSessionDetectedAction=primary-- how would I discover what is logging in, if that is indeed the issue?

**Comment by rlktradewright** [comment]
But does your task use Task Scheduler's features to restart it if it finishes or aborts? I mean things like 'Repeat task every n minutes' in the trigger definition? If you don't use /INLINE, then these things will occur because the task will complete almost immediately.

In any case, you can easily see whether the task has been started more than once - just look in the task's History tab (if the History is disabled, then right click on the Task Scheduler Library node in the left-hand pane of the Task Scheduler management console and select 'Enable All Tasks History' - however this history will be empty at first so you'll have to start from scratch). 

The fact that this occurred on Tuesday is irrelevant. Let me explain what happens. When the sescond instance is started, it displays the 'Existing Session Detected' dialog, and if `ExistingSessionDetectedAction=manual` then the second instance just sits there waiting for the user to do something. This doesn't affect the first instance in any way: so this second instance could have been started immediately after the first (there are some technicalities here that I'll gloss over because I've already spent several hours on this issue and I need my life back!). However if someone eventually notices this dialog, and clicks the 'continue with login' button, then the second instance gets logged in and the first instance then displays the 'Re-login' dialog (which is exactly what you've been experiencing). So this could be hours or days after the second instance was started. The crucial point, though, is that someone must have noticed the second instance sitting there and pressed that button! 

Regarding diagnostic information, if you set `ExistingSessionDetectedAction=primary`, so that the first instance handles the 'Re-login' dialog, then it's possible the 'Existing Session Detected' dialog is also displayed (and handled by IBC) - this dialog does contain the IP address of the other session, so if you've got `LogComponents=activate`, then you'll be able to see this in the log file (but I'm not sure whether the 'Existing Session Detected' dialog will actually be displayed).

**Comment by rsgabriel** [comment]
>does your task use Task Scheduler's features to restart it if it finishes or aborts? 

No. Here is the exported task for your inspection: https://pastebin.com/TKpzRBfq

>The crucial point, though, is that someone must have noticed the second instance sitting there and pressed that button!

As the sole user of this server, this is not the case. 

>then you'll be able to see this in the log file

Thanks. I have this set now and will await additional reproduction / log information.

**Comment by rlktradewright** [comment]
@rsgabriel 

Any further information on this?

If all is ok now, please close the issue.

**Comment by vprelovac** [comment]
@rlktradewright 

I can confirm the re-login dialogue appearing for IB Gateway users every Sunday night.

I have contacted IB support about it and they have indeed confirmed that they are breaking the connection once a week at Sunday.

I started using IBC last week and after seeing that my system was not working this morning because of that dialogue I researched the problem and that is how I found this thread.

Another thread suggested using 'primary' as a method to reestablish session so I will see if that works next week when connection is broken.

**Comment by rsgabriel** [comment]
@vprelovac @rlktradewright - I can confirm the primary setting has resolved this issue and I have been able to run the gateway uninterrupted by this dialog since I started using it.

That said, I do use IbAutoClosedown=yes  and not over the weekend. I then use a scheduled task to run the gateway weekly

**Comment by vprelovac** [comment]
@rsgabriel at what time do you run the task?

**Comment by rsgabriel** [comment]
@vprelovac anytime after 3AM GMT Saturday (when IB's autoclosedown invokes) and before the earliest market I am using opens works for me

**Comment by rlktradewright** [comment]
@rsgabriel 

I'm confused by what you're saying. IbAutoClosedown is irrelevant for the gateway, because  auto-closedown only applies to TWS. Are you confusing this with ClosedownAt, which is driven by IBC and applies to both TWS and Gateway?

**Comment by vprelovac** [comment]
@rsgabriel Since disconnect happens on Sunday night it seems that 'primary' option is the one that keeps your setup running.

Also not sure why are you doing closedown at all, and not just have the Gateway running at all time.

**Comment by rsgabriel** [comment]
@rlktradewright 

You are correct, i was looking at the wrong config file, I use

ClosedownAt=Friday 22:00

@vprelovac 

Shutting down (daily?) is recommended by interactive brokers so I follow this advice to some degree.

**Comment by vprelovac** [comment]
@rsgabriel 

What is the source of that recommendation? I've found this: 

"The IBGateway does not need to be restarted once a day like the Trader Workstation, so it can stay up and running 24 hours over 24."

**Comment by rsgabriel** [comment]
clsoed
