### ISSUE TITLE
Error when launching TWS 1012 with IBC 3.12.0 on Linux

### ISSUE THREAD

**Issue by skdjfnd** [IbcAlpha/IBC#157]
Hello,

Launching TWS through IBC fails with the latest TWS version (1012) and the latest IBC version (3.12.0) on Linux.

Here is the full log I see after launching.

[log.ibc.error.txt](https://github.com/IbcAlpha/IBC/files/7853980/log.ibc.error.txt)

**Comment by rlktradewright** [comment]
First of all, in future please please please don't quote entire logfiles in your post: it makes life difficult for all concerned. Instead, attach the logfile to your post (using the handy 'Attach files by dragging & dropping, selecting or pasting them.' link at the bottom of the text box.

'Exit status 143' at the end of the logfile indicates that the process has received a SIGTERM signal: this means that some other process has sent this signal requesting the IBC/TWS process to shut down, for example a kill command with the appropriate option will do this. 

So this is nothing to do with IBC: you need to discover what is sending the SIGTERM and why: I can't help you with that.

**Comment by skdjfnd** [comment]
Thank you for your reply.  I apologize for the large message.  I missed the "upload a file" button.

The SIGTERM is due to the fact that I killed the process manually after some time.  What happens is that after the java error message pops up, I cannot connect to the TWS API with my program.

Note that I can make this work fine with previous versions of IBC and TWS on the same machine (specifically, TWS 983 and IBC 3.8.5).

Would you be able to help me handle the java error?  It seems to be related to a CSS tag not being handled properly.

Thanks!

**Comment by rlktradewright** [comment]
Can you please not keep editing previous posts? I've just noticed that there is now a bunch of new stuff that wasn't there before. It's fine to fix typos or whatever, but significant changes that alter the whole thrust of the thread, like adding new paragraphs, need to be in new posts. 

The Java error message is again nothing to do with IBC: it is written by TWS to stderr and that is redirected into the IBC logfile. There appears to be nothing you can do to avoid this message: I get it too. There have been such messages in past 'latest' versions of TWS, but the stable versions seem to be fine. They don't appear to occur if you run TWS from the desktop icon rather than via IBC, but that's possibly because something at a higher level is swallowing the exception. I presume the actual cause is that the SVG resource referred to is missing from the relevant jar file.

The message is harmless and doesn't affect operation of TWS, and certainly doesn't prevent API connections. So if you are failing to connect to the API, you must have something setup wrong in the TWS API configuration.

[I wrote the above before I noticed your edits to your previous post, so it's pretty irrelevant now, but having wasted the time writing it I might as well leave it in].

So this whole issue boils down to the fact that you need this in your config.ini:

`AcceptNonBrokerageAccountWarning=yes`

**Comment by skdjfnd** [comment]
This solved the issue.  Thank you for your prompt answer (and apologies for the previous posts edits, I am taking the feedback for future interactions).
