### ISSUE TITLE
displaybannerandlaunch.sh: cannot execute: Undefined error: 0

### ISSUE THREAD

**Issue by joris1995** [IbcAlpha/IBC#158]
Today I tried to install IBC on my M1 Mac mini server. 
I followed all steps in the official installation guide, except that I installed in in ~/ibc rather than /opt/ibc. 

I installed the m1 native 'offline version' of tws, and had no other option for gateway

Initially I got an error where it said I didn't have permission to run the scripts (to launch tws/gateway), but I managed to overcome that problem by running chmod 755. However, this results in another error that I cannot figure out myself, or find documentation on:

`/Users/<username>/ibc/twsstartmacos.sh: line 172: exec: /Users/<username>/ibc/scripts/displaybannerandlaunch.sh: cannot execute: Undefined error: 0`

What might cause this error and how can I resolve it? Any guidance would be highly appreciated

**Comment by rlktradewright** [comment]
I don't have any access to a Mac of any flavour, but this looks like a permission error. What else could it be? Are you sure you set the permissions on the displaybannerandlaunch.sh script as well as twsstartmacos.sh?

**Comment by rlktradewright** [comment]
Closed due to lack of further input.

**Comment by brndnmtthws** [comment]
FWIW it works fine on ARM if you just use your own JVM instead of the one supplied with the TWS installer. I have an example of how to do this [in the code on my project here](https://github.com/brndnmtthws/thetagang).

I have an M1 macbook, but I also run it on a Linux ARM box, but it only works on aarch64 (i.e., 64 bit arm). If you have something like a rasppi running 32 bit raspbian it's too much of a pain to make it work (I tried, gave up).

Hope that helps!
