### ISSUE TITLE
Username/PW does not auto-populate in TWS 1015 Standalone

### ISSUE THREAD

**Issue by fettekatz** [IbcAlpha/IBC#163]
Running on Windows 10 x64, I've been using IBC to auto-login with no issue for many past versions, always using the TWS x86 standalone version. It seems that TWS x64 never works, so I've used TWS x86 without any issue. 

Using the latest IBC 3.12.0, TWS 1012 x86 auto-populates fine, but TWS 1015 does not, neither the x86 nor the x64 versions. Any ideas?

**Comment by rlktradewright** [comment]
Ok, I experience the same thing. 

IB have changed the login dialog, but I can't immediately see why IBC isn't recognising it. It's midnight here now so I'll take a further look tomorrow.

**Comment by kulki007** [comment]
I am having the same issue with 1015. I have no issues logging in with version 1014. ANy clue whats causing this error?

**Comment by rlktradewright** [comment]
As I said yesterday, IB have changed the login dialog. So IBC doesn't recognise it. So it can't enter the username and password.

Everybody will encounter the same error with 10.15, so revert to an earlier TWS version until it's fixed.

I have actually fixed it here, but I want to deploy it properly to test it before I release it. I'm about to do that. If I have time after I've done that (it's nearly midnight here on a Sunday evening so this isn't really what I want to be doing!), I'll give you a link where you can pick up this untested version. Otherwise please just be patient.

And please don't anyone else bother to say you have the same problem. I know you do!

**Comment by rlktradewright** [comment]
You can download a beta version from here:

https://1drv.ms/u/s!AlqfLEOWDJ9Zh-klxayDSKUDSpj0Ow?e=hP849Z

It works fine as far as the login is concerned, but there may be other dialog structure changes that I haven't noticed yet that will also require action, so it's entirely at your risk.

Just copy the `IBC.jar` and `version` files from the relevant jar over your existing files. No other change necessary.

**Comment by fettekatz** [comment]
Thanks for the super quick update, auto-login for works now.

However it looks like 1015 is making me switch to a new DDE system. I'll keep using 1012 for now until I figure out how that works.

**Comment by Caceresenzo** [comment]
Hi, I am having the same problem.

In the meantime, do you know a link to download an older version of the TWS?

**Comment by rlktradewright** [comment]
You can download the current stable version of TWS from IB's website.
