### ISSUE TITLE
Can't Open API-Settings (Java Errors)

### ISSUE THREAD

**Issue by ceeyee** [IbcAlpha/IBC#167]
After updating Gateway to 981-Stable or 1015-Latest, the Settings Menu (API->Settings) can't be opened, when Gateway is launched through IBC (3.12.0).

![image](https://user-images.githubusercontent.com/17518929/166998665-60b195b2-8814-4517-baf7-10a1911868d8.png)

However, the settings can be opened when Gateway is launched manually.

Could you please fix this issue?
Thank you.

**Comment by ceeyee** [comment]
It appears that the first time a new user logs in, the API->Setting is able to open.
That's the only time it works. But after that, it won't open anymore.

**Comment by rlktradewright** [comment]
Well, it works fine for me. To give me something to work with, please attach (don't quote inline) your IBC logfile (the snippet of Gateway log in your screenshot is totally unhelpful).

**Comment by ceeyee** [comment]
Do you mean this log file? Thanks.

[IBC-3.12.0-beta.2_GATEWAY-1015_THURSDAY.txt](https://github.com/IbcAlpha/IBC/files/8636445/IBC-3.12.0-beta.2_GATEWAY-1015_THURSDAY.txt)

**Comment by rlktradewright** [comment]
Yes. Thanks.

You said you were using IBC 3.12.0, but actually you're using 3.12.0-beta.2, which is not the latest version.

So try upgrading to 3.12.0.

**Comment by ceeyee** [comment]
Same error with 3.12.0
[IBC-3.12.0_GATEWAY-1015_THURSDAY.txt](https://github.com/IbcAlpha/IBC/files/8636547/IBC-3.12.0_GATEWAY-1015_THURSDAY.txt)

**Comment by ceeyee** [comment]
Same error with 3.12.0
[IBC-3.12.0_GATEWAY-1015_THURSDAY.txt](https://github.com/IbcAlpha/IBC/files/8636554/IBC-3.12.0_GATEWAY-1015_THURSDAY.txt)

**Comment by rlktradewright** [comment]
Ok. Well, the point to make here is that IBC doesn't interfere at all when a dialog - any dialog - is displayed, unless there is some specific action that it needs to take. All it does is log the fact that the dialog has been shown (as you can see in the logfile).

And I can see from the IBC settings in the logfile that there is nothing that would warrant any intervention by IBC.

So I don't know what I can suggest. 

There are a couple of interesting things in your logfile though:

1. You're using Windows 7. My personal view is that this is not a wise choice, though I'm not going to debate the pros and cons. Given the riskiness of trading as an activity, I believe it's worthwhile doing everything possible to ensure that things are as secure as possible. Having said that, I see no reason why IBC and TWS/Gateway should not work together on Windows 7 in exactly the same way as any more recent version (and indeed, comparing your logfile with my own doesn't show up any significant differences).
2. You seem to be using a 32-bit version of Gateway, in spite of running 64-bit Windows 7. Again, I don't see why this should make any difference. But it might be worth installing the 64-bit version.

Otherwise, I have no information to go on apart from your screen shot, which in any case _looks_ exactly the same as mine, so really there's nothing more I can suggest apart from things like uninstalling and reinstalling Gateway

**Comment by ceeyee** [comment]
Thanks for your reply.
I use Windows 7 because it takes less ram, and 32 bit Gateway because 64 bit does not support Excel DDE.

I have reinstalling Java/Gateway many times and the problem persists. Don't know what's going on but thanks a lot anyway.

**Comment by rlktradewright** [comment]
Can you be a bit more specific about the symptoms. In particular, is it only the API config that you can't access? Can you expand the 'plus' symbol in the left hand panel?

What about other parts of the config dialog? Do all other dialogs work as expected? Any other odd behaviours that might throw a light on this?

Is there anything unusual about your setup or system? Are there other Java programs that you run alongside IBC/Gateway?

I'm clutching at straws here, but there must be something that's causing this. And nobody else seems to be observing this behaviour (yet), so why just you?

By the way, just uninstalling Gateway doesn't get rid of the huge configuration settings file, so when you reinstall that's all the same. It might be worthwhile uninstalling, then renaming the Jts folder, then reinstalling so you start with a blank slate. But again, I can't see why any of this would affect the way IBC and Gateway work together.

**Comment by ceeyee** [comment]
I did a fresh installation of Windows 10 (in VMWare) with Latest IBC 3.12.0 and Latest Gate 1015.
Totally new system with nothing else.
Well, same error.
![image](https://user-images.githubusercontent.com/17518929/167231223-153e9d5a-19cf-4141-9b99-3ebf617ebaf7.png)

**Comment by rlktradewright** [comment]
Ah, now we're getting somewhere.

When I repeat the steps you described (ie completely new installation, actually a 32-bit VM because it's the only one I have where Gateway wasn't already installed), I then get this message:

![Gateway-DDE](https://user-images.githubusercontent.com/7384655/167254699-73e6bb2a-1bc6-4699-8ed0-99a943c1d191.PNG)

and after that, as you say, there's no way back to the API settings. 

This is indeed nothing whatever to do with IBC: this is Gateway telling you that your installation is missing a file. You may be unaware that the original DDE software has been replaced by a Java-based DDE bridge. I'm not sure whether that is available with the 32-bit versions of Gateway, and since I don't use DDE at all I know very little about it. 

Actually, doing this again, the first time you go into the API settings, the 'Enable DDE clients' check box has a link beside it marked 'Deprecated', and if you follow that link it takes you here:

https://interactivebrokers.github.io/tws-api/dde_intro.html

which tells you about the new DDE Socket Bridge API. Perhaps you should read it...

**Comment by ceeyee** [comment]
That message box pops up because you didn't install the API package (which includes ddedll.dll).
![image](https://user-images.githubusercontent.com/17518929/167262516-e4bf5655-6140-4e2c-9a83-47b8bbcd2ceb.png)

After the API is installed, there will be no longer such message.

However, the API-Settings is still not able to open, so it is probably not related to the ddedll.dll.

**Comment by rlktradewright** [comment]
Ok, well, regardless, you're getting this problem because of something lacking in the Gateway installation, and it's nothing to do with IBC, so I'm closing this now because it's just wasting my time.
