### ISSUE TITLE
The TWS_MAJOR_VRSN Issues for 10.12

### ISSUE THREAD

**Issue by giphoneix** [IbcAlpha/IBC#176]
Build 10.12.2a, Dec 14, 2021 11:07:54 AM
-> it is 1012 (ie ignore the period after the first past of the version number).

But it will be error. When I use ' 10.12', it work?

**Comment by giphoneix** [comment]
I can just rename the IB Gateway folder name to IB Gateway 1012. If using the default name (IB Gateway 10.12) will be error.

**Comment by rlktradewright** [comment]
When you install version 10.12 of TWS or Gateway, the default installation folder name is 1012, not 10.12. For example:

`C:\Jts\ibgateway\1012`

or 

`~/Jts/ibgateway/1012`

So just use the default installation folder, set `TWS_MAJOR_VRSN=1012`, and it will work. No need to rename any folders.

**Comment by giphoneix** [comment]
> When you install version 10.12 of TWS or Gateway, the default installation folder name is 1012, not 10.12. For example:
> 
> `C:\Jts\ibgateway\1012`
> 
> or
> 
> `~/Jts/ibgateway/1012`
> 
> So just use the default installation folder, set `TWS_MAJOR_VRSN=1012`, and it will work. No need to rename any folders.

Thank you for reply. However, the default folder name is IB Gateway 10.12 on **macOS**. I have tried so many times on 3 devices. Whatever, it's solved. Thanks again!

**Comment by rlktradewright** [comment]
Ah, sorry, you did mention the default folder name is IB Gateway 10.12 in your second post, and I should have realised then that you were talking about macOS. 

I wasn't aware that the default installation folder on macOS is different from Windows and Linux: I don't have any access to a macOS computer.

Can you please clarify something: if you don't rename the installation folder, but set `TWS_MAJOR_VRSN=10.12` does it work? If not, what error message do you see?

**Comment by giphoneix** [comment]
It doesn't matter. Never mind.

If I set TWS_MAJOR_VRSN=1012, I will get this:

--> Error: Offline TWS/Gateway version 1012 is not installed: can't find jars folder

If I set TWS_MAJOR_VRSN=10.12 in gatewaystartmacos.sh, it work. But the description may be misunderstood by newcomers.

-> it is 1012 (ie ignore the period after the first past of the version number).

on macOS it should be:
-> it is 10.12 (ie ignore the period after the first past of the version number).

And I use IBC(in ib_insync). Just like:

ibc = IBC(twsVersion=1012, gateway=True, tradingMode='paper')

The twsVersion is **int**, not float. If I set twsVersion=10.12, I will get a warning. But it work too.  I just don't like any warning :)

If I want to set twsVersion=1012, the only way is rename the folder name.

**Comment by rlktradewright** [comment]
It very much _does_ matter. At the moment, the comment in the script is incorrect, and it's likely to cause others to hit the same issue as you. In fact, I'm surprised this hasn't been raised before. So I need to do something to make clear the recommended approach.

Your workaround of renaming the installation folder isn't clear. Do you mean you specify a different folder when you run the installer, or do you literally mean you install to the default and then rename the folder afterwards? The latter is not ideal, because the actual install path is held in some of the installed files (for example the .vmoptions file). Now it may be that this doesn't cause a problem currently but there's no guarantee that will always be the case.

So I think it's preferable that the advice is to install to the default, and set `TWS_MAJOR_VRSN=` to the actual folder name, ie without removing the period. This will then be different from Windows and Linux, but the comment can point that out.

I also think it's incorrect to treat the version as any kind of actual number. It's a label, not a number. There's nothing to prevent IB deciding they want to issue a version like 10.20.A, which would blow your usage out of the water. 

So what I propose to do in the next release is to change the macOS start scripts to indicate that the period is to be included in the `TWS_MAJOR_VRSN=` setting, with a comment pointing out that this is different from the Windows and Linux scripts because the default installation folder is different.

**Comment by giphoneix** [comment]
> It very much _does_ matter. At the moment, the comment in the script is incorrect, and it's likely to cause others to hit the same issue as you. In fact, I'm surprised this hasn't been raised before. So I need to do something to make clear the recommended approach.
> 
> Your workaround of renaming the installation folder isn't clear. Do you mean you specify a different folder when you run the installer, or do you literally mean you install to the default and then rename the folder afterwards? The latter is not ideal, because the actual install path is held in some of the installed files (for example the .vmoptions file). Now it may be that this doesn't cause a problem currently but there's no guarantee that will always be the case.
> 
> So I think it's preferable that the advice is to install to the default, and set `TWS_MAJOR_VRSN=` to the actual folder name, ie without removing the period. This will then be different from Windows and Linux, but the comment can point that out.
> 
> I also think it's incorrect to treat the version as any kind of actual number. It's a label, not a number. There's nothing to prevent IB deciding they want to issue a version like 10.20.A, which would blow your usage out of the water.
> 
> So what I propose to do in the next release is to change the macOS start scripts to indicate that the period is to be included in the `TWS_MAJOR_VRSN=` setting, with a comment pointing out that this is different from the Windows and Linux scripts because the default installation folder is different.

I installed to the default and then rename the folder.

“So I think it's preferable that the advice is to install to the default, and set TWS_MAJOR_VRSN= to the actual folder name, ie without removing the period. ” I absolutely agree! My solution is not elegant. It's temporary. Thank you notice my issue!
