### ISSUE TITLE
SecondFactor timeout is 180 seconds no matter what I config

### ISSUE THREAD

**Issue by wumpus** [IbcAlpha/IBC#182]
I have set SecondFactorAuthenticationExitInterval=40 in config.ini, and when I start up, the logfile says that yes, it's 40.

But the actual timeout I observe is 185 seconds.

(While I'm here, I was surprised to not get a 2fa alert for paper trading. Worth mentioning in the docs.)

**Comment by rlktradewright** [comment]
The timeout (ie the maximum time for which the Second Factor Authentication dialog remains on display if the 2FA alert is not actioned by the user) is set by IB and is always (currently) 180 seconds or thereabouts. IBC cannot influence this, and there is no real reason to want to change it.

If you read the notes for the `SecondFactorAuthenticationExitInterval` setting in config.ini carefully, you'll see that it's nothing at all to do with that timeout:

```
# It controls how long (in seconds) IBC waits for login to complete
# after the user acknowledges the second factor authentication
# alert at the IBKR Mobile app. If login has not completed after
# this time, IBC terminates.
# The default value is 40.
```

Since there's no way to set the 2FA options in Account Management for the paper trading account, there's no reason to expect that you might get the 2FA alert. I disagree that this is worth mentioning in the docs: people find out pretty quickly that it doesn't work for the paper account, and if I change the User Guide or the notes in config.ini you can guarantee that next week IB will enable it for the paper account as well and then I'll have to change it again...

**Comment by wumpus** [comment]
Indeed, I read that comment and misunderstood it! Thanks for taking the time to explain.
