### ISSUE TITLE
TWS Read only mode doesn't work 

### ISSUE THREAD

**Issue by roman1720** [IbcAlpha/IBC#183]
Hi

I'm trying to login to TWS in read only mode to avoid 2FA. I'm running Linux 64bit TWS 1020 and IBC 3.14.0

In settings, I have ReadOnlyLogin=yes but after login/password dialog is passed, it gets stuck on 2FA window. There is 'Enter read only' button but I have to click it manually. Is it bug or I'm I doing something wrong? Thank you for help.

Roman
[ibc-3.14.0_TWS-1020_Saturday.txt](https://github.com/IbcAlpha/IBC/files/10047711/ibc-3.14.0_TWS-1020_Saturday.txt)

**Comment by rlktradewright** [comment]
It works perfectly for me with TWS 1020.

Looking at your logfile, it looks like TWS is expecting 2FA via Security Code Card, rather than via IBKR Mobile. I don't have time to look at the IBC code just now, but I suspect it doesn't deal with read-only login when using the Security Code card.

I'll check this out, and fix it if I think that's the appropriate thing to do. 

In the meantime, could you install IBKR Mobile and set up for 2FA that way? Then you can do the readonly login, though you would also need to set the SecondFactorDevice setting in config.ini.

**Comment by roman1720** [comment]
Yes! After setting up mobile 2FA it works. I didn't even had to modify config.ini

Thank you
