### ISSUE TITLE
Java Agent method to bypass 2FA and restart IB Gateway

### ISSUE THREAD

**Issue by stock888777** [IbcAlpha/IBC#185]
I read these.
- https://github.com/IbcAlpha/IBC/issues/105
- https://groups.io/g/ibcalpha/topic/75805176

I modified https://github.com/docker-tws/IBC and tried the Java Agent method.
I would also recommend the Java Agent method for auto-restart, as it allows IBC to continue working.

IB Gateway basically auto-recovers, but sometimes fails.
To solve this problem, I added ConfigureAutoRestartTimeTask class, added RESTARTTIME to CommandDispatcher, and after 5 minutes of error, I set the auto-restart time to 1 minute later to recover IB Gateway.
This method is very good.

If you switch to the Java Agent method, I will help something.

**Comment by rlktradewright** [comment]
I haven't forgotten about the Java Agent method as outlined in the posts you refer to.

I've been reluctant to make this change because I really don't want to spend the time working on it, when IBC works so well as it is. It has the potential to disrupt things in unexpected ways, and I'm very wary of doing things that might detrimentally affect IBC users. I have no doubt that it's viable given enough effort and testing, and I'm pretty sure it's also a 'better' method than IBC's use of event listeners, but it wasn't available when IBC was written (pre-2003). But if it ain't broke...

Regarding the auto-restart, I'm going to do a new IBC release very soon that enables this to work properly . This has become possible due to an insight into the autorestart mechanism by a member of the IBC User Group. 

If you've done the Java Agent implementation yourself, I would consider a pull request, but it would have to be complete and very well tested on both Windows and Linux (and macOS as well if you can do this). I won't accept one that leaves me with a lot of work to do to make it fully robust.

**Comment by stock888777** [comment]
> Regarding the auto-restart, I'm going to do a new IBC release very soon that enables this to work properly . This has become possible due to an insight into the autorestart mechanism by a member of the IBC User Group.

I have read this before, but how do you do this? If you have the URL, please let me know. I cannot find it in the IBC User Group.
If that is sufficient, Java Agent is not needed.

**Comment by rlktradewright** [comment]
The clever stuff to make this work isn't visible in the IBC User Group because the discoverer communicated it to me privately, just in case I had any concerns about doing it. I decided that it all seemed pretty straightforward, and doing it via IBC is no different than what TWS/Gateway themselves do. So I don't think IB are likely to object.

What follows is a brief description of the mechanism involved.

When you login (with or without 2FA) a session token that contains your authorisation is generated cryptographically, and stored internally by TWS/Gateway (note that this session spans the entire week).

When it auto-restarts (either at the configured time or using the File | Autorestart... menu item), it stores this session token in a file in your personal settings folder called `autorestart`. It then initiates another instance of TWS/Gateway by means of the tws.exe or ibgateway.exe executables on Windows (or the corresponding scripts on Linux/macOS): this is given some additional parameters telling where to find the `autorestart` file. The new instance retrieves the session token and passes it to the IB login server (without asking for username/password, since they are cryptographically sealed within the token), which verifies it and enables TWS/Gateway to proceed.

So what the StartIBC.bat (Windows) or ibcstart.sh (Linux/macOS) script does is to intervene in the restart process by renaming the tws.exe/ibgateway.exe (or script): it does this before TWS is loaded the first time, and it renames it back again after a normal full exit. Then at restart, when TWS/Gateway tries to create the new instance, it fails (but it doesn't complain about this) and then exits. The StartIBC.bat (Windows) or ibcstart.sh (Linux/macOS) script detects that `autorestart` now exists, and it restarts IBC with the correct additional parameters passed as JVM options. TWS/Gateway then run exactly as if restarted by the 'official' restart mechanism.

Note that a consequence of this process is that you cannot start TWS/Gateway from tws.exe/ibgateway.exe (or the Linux script) once IBC is running because they have been renamed (well, I suppose you could start using the renamed items, but I haven't actually tried to see if that works and I wouldn't recommend it).

Another consequence is that you can no longer use the IbDir setting in `config.ini` to set the folder where per-user settings folders are stored: if you don't want to use the default location, you must set your custom location in the TWS_SETTINGS_PATH in the start script. This is because the IBC start script needs to know this location for restart purposes, and it doesn't currently access the config.ini file.

**Comment by stock888777** [comment]
I was surprised at this.
There is "File | Autorestart..." in TWS!!!
I didn't know that. Why doesn't IB Gateway have this?
What I really want is this.

----

Thank you for explaining the method.
I read the text five times, but please forgive me if I did not understand it correctly.

Is the purpose of this approach just to ensure that the IBC continues to work after an auto-restart?
Will the authentication be able to be skipped anytime?

**Comment by rlktradewright** [comment]
Actually it's File | Restart (my mistake), and I think it was new in TWS 1019. Why not in Gateway? Who knows...

Yes, the purpose of all this is so that you only have to go through the 2FA once a week, and IBC will be included all the time. Though it appears that if one of those situations arises where TWS would unexpectedly ask you to re-login, you may have to do it again then, so keep your phone near you! It's not clear to me what causes these events, probably temporary loss of connection.

So for the person that was recently wanting to be able to go off into the forest and leave their autotrading system printing money for them, this is for you!... I didn't think it would be possible, turns out I was wrong.

**Comment by rlktradewright** [comment]
Oh, you asked 
```
Will the authentication be able to be skipped anytime?
```
I'm not sure what you mean, but I suspect the answer is 'no'. This doesn't avoid the need for authentication whenever IB thinks it is necessary, it just keeps IBC in the loop. So I repeat, you need to have your IBKR Mobile device with you just in case: obviously you know when the first login of the week is going to happen, but re-login could be needed at any time.

But the normal daily autorestart is not one of those times.

**Comment by stock888777** [comment]
Perhaps I understand what you are trying to do.
I still continue to recommend the Java Agent method.
The Java Agent method is easier and more reliable.

This is the implementation.
https://github.com/stock888777/IBC/commit/779369d035b1429cba3390ff6a488e76e55264cb

Add this to tws.vmoptions or ibgateway.vmoptions.
```
-javaagent:/somewhere/IBC.jar=/somewhere/config.ini
```

Then start TWS or Gateway without gatewaystart.sh.

The differences in implementation are,

1. ```main()``` becomes ```premain()```.
2. Premain-Class added to build.xml.
3. Added ```JavaAgent.isGateway()``` to determine TWS or Gateway. This method is OS dependent.

Documentation has not yet been copied from docker-tws/IBC.
https://github.com/docker-tws/IBC/blob/master/userguide.md

If you adopt the Java Agent method I will create a pull request.

----

> Actually it's File | Restart (my mistake), and I think it was new in TWS 1019. Why not in Gateway? Who knows...

I really want this one in Gateway!

**Comment by wangxiaoweishy** [comment]
Actually, ibgateway has the restart configuration. See that in "Configure -> Lock and exit", and it works fine for restarting everyday and authenticating once time a week, unless that you restart it manually or other unexpected situations that need to close ibgateway. My version of ibgateway is 10.19

**Comment by stock888777** [comment]
> Actually, ibgateway has the restart configuration. 

Yes, I know.

This is the reason I mentioned at the beginning. I quote from my own post.

> IB Gateway basically auto-recovers, but sometimes fails.

This is the solution. This modifies "Configure -> Lock and exit".

> To solve this problem, I added ConfigureAutoRestartTimeTask class, added RESTARTTIME to CommandDispatcher, and after 5 minutes of error, I set the auto-restart time to 1 minute later to recover IB Gateway.

But the best solution is the Restart menu item.

**Comment by stock888777** [comment]
OK. You have chosen the renaming method. I'll close this issue.
