### ISSUE TITLE
Login dialog doesn't dissapear after auto-restart

### ISSUE THREAD

**Issue by ValeryNo** [IbcAlpha/IBC#186]
Thanks for releasing a version with auto-restart support, this is a big help.

It works but I noticed that login window doesn't get closed. Over time, as many of them as there were restarts pile up which might lead to issues down the road.

Attached video demo.
![2022-11-30_18-57-55 (1)](https://user-images.githubusercontent.com/6953938/204956442-997b486d-b168-4c08-93bc-224e90d83c25.gif)

**Comment by rlktradewright** [comment]
Ok, thanks. I've investigated this and realised I made a silly mistake in the scripts for all platforms. In some situations this might mean that auto-restart doesn't work reliably for Gateway. 

I'm working on a fix and will push an update to the scripts, and re-release the .zips, just as soon as I can (may not be today).

In the meantime, it would be very helpful if you could provide me with some information, since I don't have access to a macOS computer. The installers for TWS and Gateway create items that you can use to start the programs manually (ie not using IBC). These used to be as follows (where nnn is the version number):

`~/Trader Workstation nnn/Trader Workstation nnn.app`
`~/IB Gateway nnn/IB Gateway nnn.app`

Can you please verify that this is still the case, and if not let me know where they are now? Thanks

**Comment by ValeryNo** [comment]
Hi Richard, this is VNC window to Ubuntu running inside Docker. I do have a Mac though and recent Gateway default install is 
"~/Applications/IB Gateway 10.19/IB  Gateway 10.19.app"
TWS (self-update):
"~/Applications/Trader Workstation/Trader Workstation.app"

I use none of those for IBC, this is just for the info on Mac.

The machine in this issue is Ubuntu with IB's ibgateway-stable-standalone-linux-x64.sh version of Gateway.

**Comment by rlktradewright** [comment]
Ok. It looked like the mac control buttons in the top left Anyway the changes I need to make apply to all platforms.

But you've given me the info I need, so that's fine.

**Comment by rlktradewright** [comment]
Fixed in Release 3.15.1
