### ISSUE TITLE
v3.15, MacOS, will not find jars folder

### ISSUE THREAD

**Issue by SidGoy** [IbcAlpha/IBC#187]
Mac M1:

Tried everything I could think of from the full path(installed in default/recommended location). But Jars folder won't be found. TWS 10.20 version.

Everything was working fine with v3.14 on Mac M1.

In the user guide it was mentioned to use the version number without the decimal. However on Mac M1 it works only with `10.20` as version number.

Just a heads up.

Great work and thanks for the hard work.

**Comment by rlktradewright** [comment]
It would help if you could submit the IBC logfile from one run. Just attach it, don't quote it.

I'm already aware that there's a macOS issue which might affect autorestart, but I'm slightly surprised it's not finding the jars folder. The logfile will really help.

**Comment by walterdolce** [comment]
There is an error in the way a local var assignment is done in the shell script. The MR referenced fixes it.

**Comment by walterdolce** [comment]
> In the user guide it was mentioned to use the version number without the decimal. However on Mac M1 it works only with 10.20 as version number.

This should also be fixed in the docs. It's no longer "use 1020 without dots", but the opposite (use 10.20 as mentioned by the user)

**Comment by SidGoy** [comment]
> It would help if you could submit the IBC logfile from one run. Just attach it, don't quote it.
> 
> I'm already aware that there's a macOS issue which might affect autorestart, but I'm slightly surprised it's not finding the jars folder. The logfile will really help.

I deleted the folder where I was logging it, to check whether the older version could find the Jars folder. Thanks for all the work.



> There is an error in the way a local var assignment is done in the shell script. The MR referenced fixes it.

Thank you for the fix. Would I download the same version, v3.15, to get the changes made?

**Comment by rlktradewright** [comment]
@walterdolce  Thanks for the fix. I've updated the User Guide. Note that the start scripts for macOS already noted the correct derivation.

@SidGoy This fix should at least get you going. You'll have to download the macOS script directly from here (or edit them yourself in your installation), because I haven't updated the zip files yet. 

But the other issue with the macOS (and Linux) scripts is still open. this may result in auto-restart not operating correctly (it will auto-restart, but the restarted instance may not be running under IBC). I'll get this sorted later today.
