### ISSUE TITLE
support security code cards

### ISSUE THREAD

**Issue by hroptatyr** [IbcAlpha/IBC#190]
Hiya,
I'm affected by the recent mandatory 2nd factor enrollment. However, I'm still using those old security cards. So I came up with this fix:

    diff --git a/src/ibcalpha/ibc/SecondFactorAuthenticationDialogHandler.java b/src/ibcalpha/ibc/SecondFactorAuthenticationDialogHandler.java
    index 8b75787..bddcd39 100644
    --- a/src/ibcalpha/ibc/SecondFactorAuthenticationDialogHandler.java
    +++ b/src/ibcalpha/ibc/SecondFactorAuthenticationDialogHandler.java
    @@ -67,7 +67,8 @@ public class SecondFactorAuthenticationDialogHandler implements WindowHandler {
             // For TWS this window is a JFrame; for Gateway it is a JDialog
             if (! (window instanceof JDialog || window instanceof JFrame)) return false;
             
    -        return SwingUtils.titleContains(window, "Second Factor Authentication");
    +        return SwingUtils.titleContains(window, "Second Factor Authentication") ||
    +            SwingUtils.titleContains(window, "Security Code Card Authentication");
         }
    
         private void doReadonlyLogin(Window window){

**Comment by rlktradewright** [comment]
Thanks.

Can you please clarify these points (since I have both security card and IBKR mobile I can't test the fix): 

* what happens without this amendment? Presumably you have to manually progress the logon, including if you only want read-only login?

* with the amendment, presumably the `ReadOnlyLogin` setting is actioned automatically, but manual action is required if this is not set?

* any other effects of this amendment?

**Comment by hroptatyr** [comment]
- correct
- correct
- not that I noticed (but it's only been tested for a day and a half)

**Comment by rlktradewright** [comment]
Code has been amended and will be included in next release

**Comment by joshuapack** [comment]
Do we have an estimate when the nest release is?

**Comment by rlktradewright** [comment]
No.

In the meantime, here's a beta version for you to check out:

https://1drv.ms/u/s!AlqfLEOWDJ9Zh-klxayDSKUDSpj0Ow?e=F5xskC

**Comment by rlktradewright** [comment]
Well you presumably are aware that 2FA is now mandatory (since you refer to this in your first post).

So if you only have a physical card, then the only way you can authenticate is to enter the code as instructed in this dialog. IBC can't do that for your.

The only other alternative is to log-in read-only, and I thought that was precisely the point of your post, because before this amendment IBC wouldn't honour the `ReadOnlyLogin' setting if you only had the physical card.

By far the best way to proceed is to just use the IBKR Mobile app, and then your authentication can be automated.

**Comment by joshuapack** [comment]
Oh haha, I'm a different guy, not OP. I tried `ReadOnlyLogin` but was unsuccessful as well. I will try out the IBKR Mobile app. Thanks.

**Comment by rlktradewright** [comment]
Oh, so you are! Sorry about that - don't know how I didn't spot that. Duh...
