### ISSUE TITLE
The settings dialog crashed after login

### ISSUE THREAD

**Issue by rhdlmv** [IbcAlpha/IBC#192]
[log.zip](https://github.com/IbcAlpha/IBC/files/10285769/log.zip)

I have only modified IbLoginId/IbPassword/TradingMode/AutoRestartTime, but I cannot close the setting window after logging in successfully.

How to make it work?

Version: IBCWin-3.15.2

**Comment by rlktradewright** [comment]
I can't reproduce this. I tried it with your files (my user id and password of course,), and it was ok 

The only thing I can suggest is that you set `AcceptNonBrokerageAccountWarning=yes` in `config.ini`, to see if that helps.

**Comment by rhdlmv** [comment]
Thanks
There are two cases:
1. The first login probability failed
2. If you have logged in before, there will be no problems later

Reproduction steps:
1. Delete user related files
2. Start IBC again, and settings dialog stuck. (Sometimes successful)

https://user-images.githubusercontent.com/10293599/209420775-80c0f466-acc0-4733-adc6-1cb8bdebd0c9.mp4

**Comment by candanakyol** [comment]
I worked around this by adding the following lines to `jts.ini` in `TWS_PATH`

```
[u:your_user_id_here]
AutoRestart=1
```

**Comment by rhdlmv** [comment]
Yes, I noticed that.

But in my application scenario, for a new user, I only know the username and password but not the userId. I must log in first to have a userId, but it is stuck when I log in. Does that mean I must be stuck once before I can use it normally?

How do I know the userId before log in? Or how it is calculated?

**Comment by rhdlmv** [comment]
> I worked around this by adding the following lines to `jts.ini` in `TWS_PATH`
> 
> ```
> [u:your_user_id_here]
> AutoRestart=1
> ```

**Comment by rlktradewright** [comment]
Ok, you're right, there definitely is an issue when running the very first time. I'll look into it.

However it's nothing to do with the contents of jts.ini. Adding those lines may appear to have worked, but I suspect it's more a matter of timing and was just lucky.

The actual cause is that IBC is trying to configure the autorestart time before Gateway is properly ready. You can confirm that by removing that setting from `config.ini`, and then it starts fine.

I'll get this fixed soon.

**Comment by rlktradewright** [comment]
An update on this. 

The cause of this problem is that when `AutoRestartTime` is set in config.ini (and was previously not set, as is the case for a new installation of Gateway), IBC sets the required value in the Lock and Exit section of the global configuration dialog, and this can be seen in the logfile. Next, for both Gateway and TWS, they display a dialog that warns the user to take account of the impact of this setting: this dialog contains an OK button that IBC will automatically click, so that the user should never actually see the dialog at all because IBC clicks the button very quickly. This works fine for TWS, but for Gateway for some reason the dialog is not displayed and Gateway just hangs.

My investigations indicate that this dialog is not displayed as a result of the Gateway's event dispatch thread being blocked.

However if you do this manually (ie run Gateway using IBC without the `AutoRestartTime` setting and then set the Auto-Restart time in the Lock and Exit settings) it all works as expected: the dialog is displayed correctly, IBC instantly clicks the OK button and Gateway proceeds as normal.

Therefore the blocking of the event dispatch thread must be due to something IBC is doing. At the moment I have no idea as to what this might be, or why the same thing doesn't happen with TWS.

Until I get this fixed, the only way to set the Auto-Restart time for Gateway is to do it manually.

**Comment by rlktradewright** [comment]
Ok, I've found the cause of the problem and fixed it here, but not yet released the update. It was a result of setting a variable to null too early.

Fixing that has highlighted another issue that I need to address before I release it. I hope to release by the start of next week.
