### ISSUE TITLE
2FA via SMS

### ISSUE THREAD

**Issue by Plumakeem** [IbcAlpha/IBC#196]
It would be great to support the 2nd factor authentification method via sms. The way I imagine it is that IBC receives the code via command server input and enters it automatically (here is the regarding dialog for tws):
![grafik](https://user-images.githubusercontent.com/29465925/213949729-1042ebbc-b9ea-4eb1-9b3c-a3a1b6cca8a9.png)

**Comment by rlktradewright** [comment]
I can't see the point, given that 2FA works so well via the IBKR Mobile app.

Can you provide a realistic scenario where this might be useful or preferable to IBKR Mobile?

**Comment by Plumakeem** [comment]
Well, realistic is always in the eye of the beholder. The relevant case for me is if someone does not own an IBKR Mobile capable device but only a cell phone for SMS and phone calls and a computer/Internet capable device without IBKR Mobile support. In this case, only verification via SMS is possible.

**Comment by rlktradewright** [comment]
Well, I used to be exactly the person in this situation, except even worse. I live in a place where, for geographic reasons (basically large volumes of Mother Earth in the way) there is no mobile phone signal at all. I had a fine Windows 10 Phone for use with wi-fi and when out-and-about, but SMS messages were a non-starter and a constant source of frustration because so many times there was no recognition by providers that not everyone can receive SMS.

When IBKR Mobile appeared, it was no use to me as it didn't support Windows Phone. And I wasn't going to fork out for an Android device just for 2FA to IB (my Windows phone did everything else I needed, so there would have been no other benefit).

But when wi-fi calling (ie phone calls to the mobile network using wi-fi) became widely supported, that changed the equation, because it enabled me to make cheap phone calls from home via the mobile rather than the absurdly expensive land line. So I finally acquired an Android device, and started using the 2FA via IBKR Mobile. (And now I have a VOIP service which allows me to make free calls via a SIP client on the phone from anywhere that has an internet connection, so I don't even need the wi-fi calling now.)

The moral of this little tale is that sometimes it's worth spending a relatively small amount to gain a large benefit - and cheap Android phones are not bank-breaking. And if we're being realistic, then if your friend can't afford a cheap Android device, they certainly can't afford any kind of trading!

In any case, I don't really see how what you suggest is going to help much. It wouldn't be useful if the person is at the same location as their TWS - they might as well just type the SMS code straight into the TWS dialog. So it's only really relevant if they're away from base, and then they would need to have their phone configured with a telnet client and an SSH tunnel to TWS so that the connection to the command server comes from a predictable address (it will only accept connections from addresses declared in config.ini). Are there non-Android/iOS phones that would allow you to do this?

**Comment by rlktradewright** [comment]
@janionaio Thanks for your supportive words.

@Plumakeem Ok I understand what you're saying, but the simple fact is that I can't justify the time that would be needed to implement this, given that there are probably very few other users in the same situation. (If there are, please say so here...)

If I were somehow able to charge my time spent on IBC at a realistic rate, the time to implement this would be worth a LOT more than the cost of an up-to-date iPAD...

**Comment by Plumakeem** [comment]
No problem, I can fully understand, I just wanted to ask if it would be possible. Of course, also a big thank you from me for the great work @rlktradewright!
