### ISSUE TITLE
Run this and ib gateway in Debian or Ubuntu in fully headless mode

### ISSUE THREAD

**Issue by anarchy89** [IbcAlpha/IBC#202]
Is it possible to run this and ib gateway in Debian or Ubuntu in fully headless mode?

**Comment by rlktradewright** [comment]
Yes it is possible.

Because ibgateway is a GUI application, you have to install something that makes it think there is a X-windows server. One way is to install xvfb. This handles all the X11 protocol exchanges with ibgateway but without actually displaying anything.

See https://en.wikipedia.org/wiki/Xvfb

For a detailed account of this plus a lot more see this:

https://dimon.ca/how-to-setup-ibc-and-tws-on-headless-ubuntu-in-10-minutes/

**Comment by anarchy89** [comment]
@rlktradewright 

i tried setting it up.

when i login to the server using xrdp, i am able to launch using ./opt/ibc/twsstart.sh

but when I try to launch it remotely in headless mode using an ssh server it doesnt launch. Is something like that possible with xrdp or does it have to be xvfb?

**Comment by rlktradewright** [comment]
No idea. I've never tried doing this myself.

Bear in mind that the "Reading layout settings..." state can take quite a while, so make sure you're giving it enough time.

Also, please attach your IBC logfile to your reply - it contains a mass of useful diagnostic info, and might just help.

Also it might be worth detailing what you actually did to get it this far.

**Comment by gnzsnz** [comment]
i'm maintaining a docker imager that runs ib gateway, with ibc in headless mode. you can access i through VNC

https://github.com/gnzsnz/ib-gateway-docker

**Comment by rkohli3** [comment]
> I managed to get it running but its stuck on TWS loading stuck on "Reading layout settings..." any ideas?

I had the same issue when I was running on ec2. I upgraded my ec2 from micro to large, and voila worked. I def thought it was because of the processing power.
