### ISSUE TITLE
3.16.2 auto login doesn't works on ibgateway version 10.22

### ISSUE THREAD

**Issue by yujinkai1978** [IbcAlpha/IBC#206]
version 10.20 or 10.21 works well but 10.22 don't fill user id and password correctly.

**Comment by rlktradewright** [comment]
I've pushed new `IBC.jar` and `version` files, which you can pick up from https://github.com/IbcAlpha/IBC/tree/master/resources

So you can download them directly and overwrite your existing copies.

NB: I inadvertently misnamed the commit to mention 3.16.2 instead of 3.16.3, but if you use these new versions you will indeed get 3.16.3.
