### ISSUE TITLE
"Enable ActiveX and Sockets Clients" is missing

### ISSUE THREAD

**Issue by ExpDev07** [IbcAlpha/IBC#208]
Hi! I installed IB Gateway 10.19 and notice that the "Enable ActiveX and Sockets Clients" setting in API settings is missing? I have a free trial account. Thanks!

**Comment by rlktradewright** [comment]
Well that's too bad. I don't know what you think raising the issue here could possibly accomplish.

IBC has absolutely no influence over the content of Gateway or TWS dialogues. 

So it sounds like you can't use the API with a free trial account. I've no idea whether that's the case myself, but it looks that way doesn't it? 

Why don't you ask IB directly?

**Comment by cnpatel714** [comment]
smart ass
