### ISSUE TITLE
Issue with not populating login/password; manual login causes crashing of ibgateway

### ISSUE THREAD

**Issue by sharpkids** [IbcAlpha/IBC#211]
I am experiencing a weird issue with 3.16.2 and IBGateway 10.22 where IBC would not automatically log in (login/password not automatically populated) and if I try to login manually, I can see IBGateway continuing to load and then it crashes. This set up worked well for over a year and I can't pinpoint any changes on my side except updated IBC/IBGateway versions). I tried supplying username/password to ibcstart.sh via command arguments instead of config.ini, also tried older versions of IBC but nothing helped so far and I am not sure what else to try. If I replace a call to ibcstart.sh and start ibgateway directly, I can manually log in just fine and everything works without crashing.

[ibc.log](https://github.com/IbcAlpha/IBC/files/11444620/ibc.log)

**Comment by sharpkids** [comment]
Will try that, thank you!

**Comment by sharpkids** [comment]
Tried it with TigerVNC but that didn't help:

New Xtigervnc server '297a6ddfedc1:0 (root)' on port 5900 for display :0.
Use xtigervncviewer -SecurityTypes VncAuth,TLSVnc -passwd /root/vnc/passwd 297a6ddfedc1:0 to connect to the VNC server.


================================================================================

Starting IBC version  on 2023-05-10 at 21:22:27

Operating system: Linux 297a6ddfedc1 5.19.0-41-generic #42~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Tue Apr 18 17:40:00 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

Arguments:

TWS version = 1022
Program = Gateway
Entry point = ibcalpha.ibc.IbcGateway
--tws-path = 
--tws-settings-path = 
--ibc-path = 
--ibc-ini = /root/ibc/config.ini
--mode = 
--java-path = 
--user =
--pw =
--fix-user =
--fix-pw =

=================================
Generating the classpath
Classpath=/root/Jts/ibgateway/1022/jars/jackson-core-2.12.3.jar:/root/Jts/ibgateway/1022/jars/jts4launch-1022.jar:/root/Jts/ibgateway/1022/jars/jxbrowser-7.29.jar:/root/Jts/ibgateway/1022/jars/jxbrowser-linux64-7.29.jar:/root/Jts/ibgateway/1022/jars/jxbrowser-swing-7.29.jar:/root/Jts/ibgateway/1022/jars/locales.jar:/root/Jts/ibgateway/1022/jars/log4j-api-2.17.1.jar:/root/Jts/ibgateway/1022/jars/log4j-core-2.17.1.jar:/root/Jts/ibgateway/1022/jars/total-2020.jar:/root/Jts/ibgateway/1022/jars/twslaunch-1022.jar:/root/Jts/ibgateway/1022/jars/twslaunch-install4j-1.12.jar:/root/Jts/ibgateway/1022/.install4j/i4jruntime.jar:/opt/ibc/IBC.jar

Generating the JAVA VM options
autorestart file not found

Java VM Options=-Xmx768m -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -XX:ParallelGCThreads=20 -XX:ConcGCThreads=5 -XX:InitiatingHeapOccupancyPercent=70 -Dtwslaunch.autoupdate.serviceImpl=com.ib.tws.twslaunch.install4j.Install4jAutoUpdateService -Dchannel=latest -Dexe4j.isInstall4j=true -Dinstall4jType=standalone -DjtsConfigDir=/root/Jts

Determining the location of java executable
Location of java executable=/usr/local/i4j_jres/Oda-jK0QgTEmVssfllLP/1.8.0_202/bin

Renaming IB's TWS or Gateway start script to prevent restart without IBC

Starting Gateway with this command:
"/usr/local/i4j_jres/Oda-jK0QgTEmVssfllLP/1.8.0_202/bin/java" -cp "/root/Jts/ibgateway/1022/jars/jackson-core-2.12.3.jar:/root/Jts/ibgateway/1022/jars/jts4launch-1022.jar:/root/Jts/ibgateway/1022/jars/jxbrowser-7.29.jar:/root/Jts/ibgateway/1022/jars/jxbrowser-linux64-7.29.jar:/root/Jts/ibgateway/1022/jars/jxbrowser-swing-7.29.jar:/root/Jts/ibgateway/1022/jars/locales.jar:/root/Jts/ibgateway/1022/jars/log4j-api-2.17.1.jar:/root/Jts/ibgateway/1022/jars/log4j-core-2.17.1.jar:/root/Jts/ibgateway/1022/jars/total-2020.jar:/root/Jts/ibgateway/1022/jars/twslaunch-1022.jar:/root/Jts/ibgateway/1022/jars/twslaunch-install4j-1.12.jar:/root/Jts/ibgateway/1022/.install4j/i4jruntime.jar:/opt/ibc/IBC.jar" -Xmx768m -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -XX:ParallelGCThreads=20 -XX:ConcGCThreads=5 -XX:InitiatingHeapOccupancyPercent=70 -Dtwslaunch.autoupdate.serviceImpl=com.ib.tws.twslaunch.install4j.Install4jAutoUpdateService -Dchannel=latest -Dexe4j.isInstall4j=true -Dinstall4jType=standalone -DjtsConfigDir=/root/Jts ibcalpha.ibc.IbcGateway "/root/ibc/config.ini"  

Error: Could not find or load main class ibcalpha.ibc.IbcGateway
IBC returned exit status 1
autorestart file not found

Gateway finished

**Comment by rlktradewright** [comment]
[_Please can I ask you in future to attach log files rather than quote them inline - quoting them makes the posts very unwieldy, and if they're attached as files it's much easier to do things like comparing them with other files. Also always attach the whole of a log for a run, not just extracts_.]

This problem is nothing to do with vnc, so trying different versions of that is not going to make any difference.

The error message means that IBC.jar is not in the location that it's supposed to be. You haven't supplied a value for the --ibc-path argument, so it defaults to /opt/ibc. It appears that IBC.jar is not there.

I've just uploaded a new IBC.jar version 3.16.4-beta.2 to the repository, so you might as well download it from https://github.com/IbcAlpha/IBC/tree/master/resources. Make sure you put it in /opt/ibc, and also ensure you set execute permission. Also please make sure the `version` file (also in /opt/ibc) contains just the version number, ie `3.16.4-beta.2`.

**Comment by sharpkids** [comment]
OK, thank you, I will try that shortly. The reason I decided to try TigerVNC is actually due to your comment :) https://github.com/IbcAlpha/IBC/issues/210#issuecomment-1523108902

**Comment by sharpkids** [comment]
Sorry for the delay, I was unable to complete this yesterday. I have now confirmed that the 3.16.4-beta.2 resolves this issue. Thanks again!

**Comment by rlktradewright** [comment]
Let's be clear here: there is nothing in the 3.16.4-beta.2 that would have made the sligtest difference. The problem was that you didn't do the previous 3.16.3 upgrade properly, so either IBC.jar wasn't there at all, or you hadn't set execute permission on it. Presumably you have now done it correctly with 3.16.4-beta.2, and that's the only reason it is now working: there _are_ changes in 3.16.4-beta.2, but they are only relevant if you're using the FIX Gateway rather than the standard Gateway, and you aren't.

3.16.3 works perfectly with Gateway 10.22. I use it all day every day.

**Comment by sharpkids** [comment]
OK, sounds good. I am closing this issue now.
