### ISSUE TITLE
Auto-Restart doesn't work - autorestart file not found

### ISSUE THREAD

**Issue by hoffer** [IbcAlpha/IBC#221]
TWS version - 10.23(.2a)
IBC version - IBCWin-3.17.2

I'm trying to upgrade to TWS 10.23 with latest IBC, after configuration, I started with StartGateway.bat without any issue. However, when it is time to auto-restart (at 22:53), the IBC exits, the log shows "autorestart file not found".

I can find the autorestart file under C:\workspace\IBCWin-3.17.2\AccountDirs\acc10000\akeegogbionginijjfcjmkllkhloaiocnamgoaid\autorestart  now sure why IBC cannot find it. (see log below) 

================================================================================
Starting IBC version 3.17.0 on 2023/07/02 周日 at 22:51:26.04

Operating system:  Microsoft Windows 11 Pro  64-bit          10.0.22621  

Arguments:

TWS version = 1023
Program = Gateway
Entry point = ibcalpha.ibc.IbcGateway
/TwsPath = C:\Jts
/TwsSettingsPath = C:\workspace\IBCWin-3.17.2\\AccountDirs\acc10000\
/IbcPath = C:\workspace\IBCWin-3.17.2\
/Config = C:\workspace\IBCWin-3.17.2\\AccountDirs\acc10000\ibcontroller-acc10000.ini
/Mode = 
/JavaPath = 
/User =
/PW =
/FIXUser =
/FIXPW =

...
...
...

2023-07-02 22:53:00:258 IBC: detected dialog entitled: Restart in progress; event=Activated
2023-07-02 22:53:00:262 IBC: detected dialog entitled: Restart in progress; event=Focused
2023-07-02 22:53:00:262 IBC: detected dialog entitled: Restart in progress; event=Opened
2023-07-02 22:53:00:263 IBC: detected frame entitled: U9085792 Exit Session Setting; event=Closed
2023-07-02 22:53:00,797 JTS-IA Stopper-101 ERROR Attempted to append to non-started appender d
2023-07-02 22:53:00,798 JTS-IA Stopper-101 ERROR Attempted to append to non-started appender d
2023-07-02 22:53:00,799 NIA-Input-Queue-2 ERROR Attempted to append to non-started appender d
2023-07-02 22:53:00,800 NIA-Input-Queue-2 ERROR Attempted to append to non-started appender d
2023-07-02 22:53:03,426 pool-3-thread-1 ERROR Attempted to append to non-started appender f
Program has exited
Error level is 0
Check for 2FA dialog timed out
Check for login dialog display timeout
Check for restart
call :GetAutoRestartOption
Finding autorestart file
autorestart file not found
Normal exit

Gateway finished at 2023/07/02 周日 22:53:04.23

IBC running GATEWAY 1023 has finished at 2023/07/02 周日 22:53:04.23

**Comment by rlktradewright** [comment]
I reconfigured my paper trading account to use exactly the same folders and filenames as you. I copied over the existing TWS settings to the new settings folder. Then I ran gateway 10.23, and configured auto-restart for 11:35 AM.

It all worked perfectly.

I've attached my IBC logfile, GatewayStart.bat and .ini files so you can compare them with your own to see if you've maybe got something set up wrong. (The .bat and .ini files have been given .txt extensions to enable them to be uploaded.)

[IBC-3.17.0_GATEWAY-1023_MONDAY.txt](https://github.com/IbcAlpha/IBC/files/11936176/IBC-3.17.0_GATEWAY-1023_MONDAY.txt)
[ibcontroller-acc10000.txt](https://github.com/IbcAlpha/IBC/files/11936189/ibcontroller-acc10000.txt)
[StartGateway.txt](https://github.com/IbcAlpha/IBC/files/11936190/StartGateway.txt)

If you can't find anything, then attach your versions of those files to your reply - don't forget to obscure your user id and password in the .ini file. And please include the whole of the logfile, not just extracts from it.

**Comment by hoffer** [comment]
I found the issue. I copied the wrong logs.... the actual error log should be 
```
/TwsSettingsPath = C:\workspace\IBCWin-3.17.2\\AccountDirs\acc10000
/IbcPath = C:\workspace\IBCWin-3.17.2\
/Config = C:\workspace\IBCWin-3.17.2\\AccountDirs\acc10000\ibcontroller-acc10000.ini
```

There was an additional '\' before **AccountDirs** in the path. previous IBC this won't cause an issue, however, start from 3.17 this caused the auto-restart to fail. I fixed it by updating my script with one less `\`, however, I think it could also be solved in StartGateway.bat by trim the additional '\'. but at this point I didn't know where exactly need to be fixed.

**Comment by rlktradewright** [comment]
Thanks for that information.

I have pushed a fix that prevents this, and the updated file will be included in the zip for the next release. But not important enough to do a release just for this.

**Comment by tredondo** [comment]
Ran into the same error on Ubuntu. I wasn't aware of an autorestart file - looks like a new mechanism since the last time I used IBC.

I'll read up on that and try to fix the error. In the meantime may I suggest enhancing the error message to contain the expected path of the autorestart file, or the actual path that didn't point to one, or where it should be configured?

**Comment by rlktradewright** [comment]
The autorestart file is created by TWS/Gateway jut before it autorestarts. It is an encrypted file containing login credentials and authentication tokens that the restarted TWS/Gateway uses to automaticallly continue the session without prompting the user for credentials or demanding 2FA.  As soon as that has happened, TWS/Gateway deletes the autorestart file. So it's typically only in existence for a few seconds. IBC has no involvement in the creation and use of the autorestart file, though it does check for the existence of that file because it has to behave slightly differently in an auto-restart context.

If you've never used auto-restart it's more than likely you'll never have seen this file, because it won't ever have ben created, and even when it is you have to be watching like a hawk (in the right place) to see it be created and then deleted seconds later.

Auto-restart was introduced in TWS/Gatway in v974, several years ago now.  IBC has supported it since v3.15.0 (end of November 2022).

Regarding the User Guide, the very first paragraph talks about auto-restart, and it refers to a later section that contains some potentially helpful tips.

IBC has no way of knowing where the autorestart file should be. Life would be a lot simpler if it did! So the existing error message is the best it can do. Even if it could tell you where it should be, that isn't going to help you at all - you can't create it yourself.

If you're getting this error and you're on the current version of IBC, then attach your IBC logfile, your start script and your config.ini to your reply. If you're not on the current IBC version, then move to it.

Re timezones, I suspect the auto-restart time is specified in the timezone that TWS/Gateway is configured for, but I don't know for sure. To be honest I can't be bothered to find out: you'll soon discover if you get it wrong, and TWS/Gateway itself doesn't make this clear in the config dialog.

**Comment by tredondo** [comment]
Thank you for the reply. I've been using IBC 3.18.0, after upgrading from 3.12.

After I log into IB Gateway using IB Key, it exits after several hours. This has happened twice over the past 24 hours (during the weekend, so I thought the first time was the weekend autorestart). I can't tell from the Gateway log why it exited.

I was also expecting that IBC would restart it regardless of the exit reason, but maybe that's incorrect?

* IBC logile: [ibc-3.18.0_GATEWAY-1019_Monday.txt](https://github.com/IbcAlpha/IBC/files/12714022/ibc-3.18.0_GATEWAY-1019_Monday.txt)
* start script: [gatewaystart.sh.txt](https://github.com/IbcAlpha/IBC/files/12714040/gatewaystart.sh.txt)
* ~/ibc/config.ini: [config.ini.txt](https://github.com/IbcAlpha/IBC/files/12714052/config.ini.txt)
* Gateway logfile from ~/Jts: [launcher.log](https://github.com/IbcAlpha/IBC/files/12714074/launcher.log)

**Comment by rlktradewright** [comment]
First, the comments for the `AutoRestartTime` setting in `config.ini` say this:

# The normal way to configure the time at which this happens is via the
# Configuration dialog. Once this time has been configured in this way, the
# setting persists until the user changes it again.

It then tells you the circumstances when you mnight need to set this setting. Since those circumstances don't apply to you, you don't need to set it. If you do set it, it won't cause any problems: the value in the setting will be used, and ihat value will be saved by TWS/Gateway. So the next time you run it, you'll just be setting the same value again.

Next, the message 'autorestart file not found' that you see in the IBC logfile is not an error message: it's just a statement of fact, and is really a diagnostic message for my benefit. When TWS/Gateway shut down, the IBC script has no idea whether TWS/Gateway is auto-restartng until it checks for the autorestart file: if it doesn't find it, it knows that this is a 'normal' exit, and the script exits. If it does find it, it does something different to cause TWS/Gateway to be reloaded and auto-restart to proceed.

So you are not at all in the same situation that this Issue was originally concerned with, which was the autorestart file not being found when it did actually exist.

I have no idea why Gateway shut down at 2023-09-25 04:47:22:711: this just looks like a perfectly normal exit as a result of user action. It's certainly nothing to do with IBC. I think you'll need to contact IBKR if you didn't initiate the shutdown.

Finally IBC never restarts automatically after a normal shutdown. If you want this to happen, you have to make your own arrangements (for example using crontab on Linux, Task Scheduler on Windows: this is all covered in the User Guide).
