### ISSUE TITLE
Weekly reconnects

### ISSUE THREAD

**Issue by meteorpublish** [IbcAlpha/IBC#23]
Apologies if I missed the note about this or if my memory is faulty.

I'm using the IB Gateway on Linux with a simple app that stores security prices. No trading, I'm just gathering data. IIRC until sometime around June, I never had to reconnect. I was using IBController. Then, I had to reconnect every Sunday.

This past week, I've moved to IBC, and around 1am Eastern, my app lost the data connection, and I got a prompt via the IB Key Android app to re-authenticate. Not a huge deal, but the problem is that I need to be awake at 1am to confirm the prompt. I'm using live (not demo) trading and have a separate account for the headless app vs. my regular account. No auto-close settings. `IbAutoClosedown=no`, `StoreSettingsOnServer=yes`.

1. Was there a change in this weekly reconnection requirement this past summer, or am I mis-remembering that I didn't have to reconnect every Sunday? Ideally I'd like to leave the app completely unattended to gather data for a few months.

2. Any chance to change the timing of the reconnect earlier in the day?

**Comment by rlktradewright** [comment]
The first thing to note is that IBC has no control at all over whether or when you have to re-authenticate using the Android app or any of the other security devices that IB supply. In fact IBC is completely oblivious to the whole process. 

So no, there is no possibility of IBC somehow 'changing the timing of the reconnect'.

The second thing is that up till recently, it was always the case that TWS/Gateway would automatically re-login when it was necessary, without using 2FA. And I've no idea what were the conditions that made auto re-login necessary, as that is entirely driven by TWS/Gateway or more likely the IBKR servers themselves. Such auto re-logins were completely out of IBC's control, because although the login dialog was actually briefly activated, and IBC would log this event, it contained nothing that IBC could interect with - in particular no login button: so IBC observed this event, but totally passively.

So yes, you do remember correctly that you didn't used to have to do the 2FA step when Gateway did its auto re-login.

What I suspect is going on now is that as a result of GDPR, IB have decided that such auto-relogins must include 2FA verification. I don't know this for a fact, but given other changes such as encrypting TWS/Gateway log files it seems quite likely to me.

The upshot of this is that there is nothing that IBC can do to ease this situation. If these unexpected authentication requests are causing you a problem, your options are limited:

1. Complain to IBKR about it and try to persuade them that this change is unhelpful - good luck with that!

1. Opt out of the 2FA mechanism for login to TWS/Gateway (you can do this via Account Management). This is what I (and I suspect most IBC users) have done. This if course means you forfeit certain guarantees that IBKR make if you're fully enrolled in 2FA, so you need to weigh up carefully whether you want to do this.

By the way, everything I've said here applies equally to IBController.

**Comment by rlktradewright** [comment]
Closed due to lack of further input.
