### ISSUE TITLE
Question: Is there any difference on launching TWS with IBC while using an ibgateway installation

### ISSUE THREAD

**Issue by gnzsnz** [IbcAlpha/IBC#239]
I've been using IBC with ibgateway for some time, always using `-g` parameter on script `ibcstart.sh`.

Recently i realized that if I remove IBC's `-g` parameter it will actually launch TWS even though I installed ibgateway and not TWS.

So my question is, is there any problem with this approach? is there any missing dependences, or consequence of runnint TWS in this way.

I find it very convenient, as with a single installation I can have both for the price of one. But i wonder if there is any known limitation on this approach.

**Comment by rlktradewright** [comment]
This is explained in the User Guide, so you are only stating what is already described there. It has always been the case that you only need to install one or the other to use both.

The Java .jar files installed by the TWS and Gateway installers are identical. What's more, they're the same on all platforms. The only thing that's different is the top-level program (on Windows) or script (on Linux/macOS), and IBC doesn't use those. The IBC script finds whatever version you've got installed, and it uses the value of the -g parameter to determine which entry point to use.

**Comment by rlktradewright** [comment]
I don't have any problem running TWS/Gateway on Linux without installing additional libraries.

Are you perhaps setting the --java-path parameter to ibcstart.sh? If so that's probably the cause of the problem. You need a good reason for setting this: the default uses the 'private' Java installation included by the TWS/Gateway installers. It contains everything you need, and is the version against which IB have developed and tested their software, so it's best to use this: it also means you don't have to install Java yourself.

To be frank, you really shouldn't be using ibcstart.sh directly yourself.  Just use the top-level IBC scripts (twsstart.sh and gatewaystart.sh) and everything will be fine.

**Comment by rlktradewright** [comment]
Ok. 

I suspect IB expect their users to be installing in a standard desktop environment, which already contains these dependencies.

Indeed, some months ago I installed a minimal Ubuntu Server just a for a bit of fun (which it wasn't!), and hit the same dependency problem. I eventually got it working, using xvfb and RealVNC to get a UI, and it ran just fine, fully automated, for a week or so, but then I reverted bak to Windows because I'm just not confident managing such a setup for the long term.
