### ISSUE TITLE
Repeated prompts from IB Key

### ISSUE THREAD

**Issue by meteorpublish** [IbcAlpha/IBC#24]
1. When the forced reconnection I mentioned in the previous issue happened, I authenticated using the IB Key Android app, data resumed arriving to my client, but then I kept getting the IB Key authentication prompt. The 4th time I got it, I tapped cancel. But, then my app stopped receiving data.

2. So I launched `/opt/ibc/gatewaystart.sh` again, remembering from the IBController days that this would not spawn a new instance, but rather "reboot" the current one. However, I ended up with two process trees (/opt/ibc/gatewaystart.sh -> java etc.).

Thought I'd report this, and happy to provide more information next Sunday.

**Comment by rlktradewright** [comment]
Closed due to lack of further input.

**Comment by meteorpublish** [comment]
> What you say in your paragraph 2 is not correct: running gatewaystart.sh again has never "rebooted" the current instance, either for IBController or IBC.

What used to happen when running IBController's `gatewaystart.sh` after it had already been launched and the Gateway was running?

What I've noticed for the first time today was that with IBC, if I run `DISPLAY=:0 /opt/ibc/gatewaystart.sh` twice (within a few seconds, Gateway starting up normally), I get

> Error: process is already running

I've never seen this message before, and I'm 99.9% sure that I did run `DISPLAY=:0 /opt/ibc/gatewaystart.sh` while the gateway was running.

Related: is there a recommended way to "reboot" the Gateway? What I currently do is run `htop` on Linux, find the `xterm` line, and kill the entire subtree of processes, if I have more than one IBC instance running (e.g. paper + real account). Otherwise, `killall xterm` seems to work.

![image](https://user-images.githubusercontent.com/10043369/60702128-fc4d8800-9ecb-11e9-839a-649248eed36d.png)

**Comment by meteorpublish** [comment]
> What you say in your paragraph 2 is not correct: running gatewaystart.sh again has never "rebooted" the current instance, either for IBController or IBC.

What used to happen when running IBController's `gatewaystart.sh` after it had already been launched and the Gateway was running?

What I've noticed for the first time today was that with IBC, if I run `DISPLAY=:0 /opt/ibc/gatewaystart.sh` twice (within a few seconds, Gateway starting up normally), I get

> Error: process is already running

I've never seen this message before, and I'm 99.9% sure that I did run `DISPLAY=:0 /opt/ibc/gatewaystart.sh` while the gateway was running.

Related: is there a recommended way to "reboot" the Gateway? What I currently do is run `htop` on Linux, find the `xterm` line, and kill the entire subtree of processes, if I have more than one IBC instance running (e.g. paper + real account). Otherwise, `killall xterm` seems to work.

**Comment by rlktradewright** [comment]
What used to happen was that the second instance would fail because the logfile was already in use by the first instance.

The message you quote is new in the latest IBC release. It enables you to start IBC periodically with crontab without the mess that would have occurred with previous versions, similar to using Task Scheduler on Windows. There is a section on this topic towards the end of the User Guide.

There is no way to 'reboot' Gateway using IBC. You have to shut it down and then restart it. To shut it down, use telnet to send a STOP command to IBC's command server port. To restart it automatically, use crontab (eg run it every 5 minutes: if it's already running, nothing much will happen; if not, a new  instance will be started.
