### ISSUE TITLE
Launching gatewaystart.sh from user crontab is impossible

### ISSUE THREAD

**Issue by yokotsumo** [IbcAlpha/IBC#249]
I am logged in with my user account on Debian 12 latest updates.
My display is 0.
I want to start IBC via crontab.
I have tried:
* * * * * export DISPLAY=:0 && /bin/bash /opt/ibc/gatewaystart.sh
* * * * * env DISPLAY=:0 /bin/bash /opt/ibc/gatewaystart.sh
* * * * * DISPLAY=:0 /bin/bash /opt/ibc/gatewaystart.sh
* * * * * env DISPLAY=:0 /bin/bash /opt/ibc/gatewaystart.sh
* * * * * su user -c "<...>"

It never works because the cron job can not open DISPLAY:=0.
The error message is:
"Authorization required, but no authorization protocol specified
Error: cannot open display: :0"

Please help.

**Comment by rlktradewright** [comment]
I'm not a Linux expert so I'm not sure what to suggest.

But here are some obvious questions:

1. Does it work when you run it manually?
2. Is your cron job set up in your user crontab?
3. What actually happens when cron tries to start the job? What does the logfile say?

I set up a cron job on my Ubuntu 22.04 earlier, and I had to use DISPLAY=:10 (like it says in the User Guide). 

I also have an Ubuntu 22.04 minimal server, and on that I have to use DISPLAY=:0.

I don't know what governs the required value of the DISPLAY variable. But it sounds to me like you just need to find the right value.

**Comment by yokotsumo** [comment]
I finally found the solution. It is in this post:
https://superuser.com/questions/759759/writing-a-service-that-depends-on-xorg?_gl=1*raop4r*_ga*MTg0MzgwNTYzOS4xNzA3NzU4OTg4*_ga_S812YQPLT2*MTcwNzc1ODk4OC4xLjAuMTcwNzc1ODk4OC4wLjAuMA..

using the service config from this post:
https://dimon.ca/how-to-setup-ibc-and-tws-on-headless-ubuntu-in-10-minutes/
