### ISSUE TITLE
Wrong Username/Password Bug TWS Paper Trading Automated Login Failure

### ISSUE THREAD

**Issue by massimo-maimeri** [IbcAlpha/IBC#256]
I get a similar issue to #251 in my VM instance on Windows 10 Pro. Every time I start the StartTWS.bat file I get an error message saying that TWS can't login because of Unrecognized Username and Password. 

The strange thing is that if I manually enter the same user & password I can log in without any problems. 

It seems to me like a typo or an automation bug. I already tested the 3.19 beta IBC version mention on #251 but the same error appear. The only difference is that now the login process will stop without the error screen displayed for more than half a second. 

I attach my last log file that my help:
[IBC-3.19.0-beta.2_TWS-1019_SATURDAY.txt](https://github.com/IbcAlpha/IBC/files/15365616/IBC-3.19.0-beta.2_TWS-1019_SATURDAY.txt)

**Comment by rlktradewright** [comment]
This doesn't make any sense.

When the login dialog is displayed, IBC reads the user id and password from config.ini and puts them in the relevant fields. There is absolutely no possibility that it will put something else in there. Therefore if it fails to login, it has to be because the user id and/or password in config.ini are not correct (unless you happen to be trying this during one of the occasional weekend periods when IB's service may not be available).

Try this: remove your user id and password from config.ini. Now run IBC: when the login dialog displays, IBC won't do anything because it has no information: so now enter your user id and password manually, and click the login button. If it logs in now, then it must be that what you had in config.ini before was wrong.

**Comment by massimo-maimeri** [comment]
That's exactly why is very, very strange. I tried few more times just to make sure everything is okay. 

When I log in manually I have no problem. If I use THE SAME username/password in the config.ini or the StartTWS.bat file and start the program..it doesn't log in. 

**UPDATE**: I find a workaround. If I put my username/password only in the config.ini and run startTWS.bat everything works fantastic. BUT If for some reason you put your credentials in the startTWS.bat or both files (config.ini and startTWS.bat) the program will block on the login screen with the error mention above. 

Mammamia 
Hope this will help some folks

**Comment by rlktradewright** [comment]
Well I have to disagree with you. I find that it works perfectly whether you put your credentials in config.ini, or in the StartTWS.bat, or in both. Note that if you put your credentials in both, then what's in config.ini is ignored, as the notes in config,ini explain.

I don't know what you're doing wrong, but you are definitely doing _something_ wrong!. This is basic, fundamental stuff, autologin is the main purpose of IBC. If it didn't work, I think somebody would have reported it sometime over the past twenty years.

Perhaps when you put them in StartTWS.bat, you're putting the user id in the password setting, and the password in the user id setting?

In any case, I seriouly recommend that you use config.ini, not the .bat file, because using the latter means that varous tools (such as Task Manager) can make the credentials visible, so it's fundamentally insecure.
