### ISSUE TITLE
Lock and Exit > Never lock Trader Workstation

### ISSUE THREAD

**Issue by wibuf** [IbcAlpha/IBC#257]
I've went through the config and the documentation, but I haven't been able to find anything about setting IBKR to Never lock Trader Workstation under the Lock and Exit configuration in the IBKR Settings. 

Is it possible to set this with IBC?

Thanks

**Comment by handelsmeisterei** [comment]
Today I woke up to a TWS version of 10.29 in my trading setup that was locked. The "Never lock Trader Workstation" setting was gone (worked fine for the last months). I have no clue how this can be circumvented. Does IBCAlpha need to refill the password as soon as TWS locks?

**Comment by wibuf** [comment]
I'm on 10.27.1f, but the locking issue started for me this morning, resolved when I manually set to Never Lock. I am guessing there was some sort of update where the TWS config was set to defaults or something.

**Comment by handelsmeisterei** [comment]
Yes, 10.27 still has that setting. In 10.28 the "Never lock" setting does not appear at all.

**Comment by wibuf** [comment]
Other users here mention the setting is back in 10.28, maybe try to restart TWS or reinstall?

https://groups.io/g/twsapi/topic/tws_option_never_lock_trader/103503025

**Comment by handelsmeisterei** [comment]
Thanks for sharing! Will retry tomorrow.

**Comment by handelsmeisterei** [comment]
can confirm that it works again.

**Comment by wibuf** [comment]
That's good news. I think this issue needs to remain open. I believe IBC should be able to set that setting during launches.

**Comment by rlktradewright** [comment]
I disagree. I don't see any reason to be able to configure this via IBC.

**Comment by wibuf** [comment]
My concern was that this setting was set to default after some sort of TWS update I believe, and affected multiple people it seems. This prevented the API from working properly, if IBC were able to set this after login the API would have continued to function properly. But I understand if that's not part of the scope of this software.

**Comment by rlktradewright** [comment]
If the setting is actually there (ie visible in the Lock and Exit dialog and not disabled), then users can just set it manually. You only need to set it once, and the setting is persisted between sessions.

If the setting is NOT there (as seemed to be the case for some users), then IBC can't possibly set it. The best it could do would be to enter the password when the user tries to access TWS while it's locked. I'd be reluctant to do this until I know why this draconian rule is being enforced (if it is, which I doubt - an error on IBKR's part seems much more likely). 

By the way, TWS being locked doesn't affect API access at all, as far as I can see.

**Comment by subes** [comment]
We are getting these errors in the occasionally when we forget to configure this in a new TWS instance:
`TWS error - [#438] The application is now locked`
After a while our API connection drops (though might also be due to an unstable internet connection).

 Would be great if IBC was able to configure this automatically because auto-restart (which can be configured by IBC fails to be configured because when auto-lock is enabled the auto-restart is disabled sadly):
![image](https://github.com/IbcAlpha/IBC/assets/332937/14740165-646a-480f-8794-20d33e9d1d3b)
(after setting never lock we can configure auto restart)
![image](https://github.com/IbcAlpha/IBC/assets/332937/e69e43fc-9340-4869-9cd1-b9f412afc065)

**Comment by rlktradewright** [comment]
Sorry for the delay in replying.

I must be missing something here. Can you explain your use case in more detail. I don't understand the following:

* why do you have to keep setting up new TWS instances? Do you have lots of different accounts?
* when you install TWS for a new account, is the 'Lock Trader Workstation after...' setting already set on?
* why can't the user just unlock it and change the setting as required?

**Comment by wibuf** [comment]
Just to add my experience with this, I've had IBC set up and working flawlessly for about a year. However, in that time, "something" on the TWS side has reset that Lock Trader Workstation to the default 30 minutes, 2-3 times. Not really breaking IBC, but preventing the automation I have set up for TWS. Not a huge deal, I manually set it back and it's good to go until next time. I know this isn't an IBC issue, but I originally created this issue figuring the goal for IBC would be complete automation of the login process of TWS, and I figured since IBC is editing settings at launch anyways that it would be beneficial to have the capability of checking that setting as well. If TWS is just going to lock after 30 minutes that's not full automation of it. But that's just my two cents, I appreciate all the work you've put into this.

**Comment by tsunamilx** [comment]
I have the exact issue as @wibuf, I am not a HK user, and I have set "Never lock workstation", it just after some time it will be reset to lock for some reason. I believe it happens after a restart, and when it happens, it happens quite often on weekend, not sure if this is relevant though.
 
I second "IBC is editing settings at launch anyways that it would be beneficial to have the capability of checking that setting as well", this could be really helpful.

@rlktradewright would you please consider this and reopen this? 

Much appreciated.

**Comment by rlktradewright** [comment]
Ok, I'll take another look at this.

Does anyone have any insight into why or when it 'forgets' the 'Never lock workstation' setting? There must be some stimulus that causes this? Frankly I don't believe that it just reverts for no reason. I have certainly never experienced this.

It might be worth pointing out that when you change something in the TWS or Gateway configuration, the revised setting is not saved in the settings file until you do a tidy shutdown or you use the `File | Layout settings | Save settings` command. If you do an untidy close (eg kill the process, close the IBC banner window, etc) before that point then when you start TWS/Gateway again the new setting will not be restored. For this reason you should always do a tidy closedown. 

So is it possible that this could somehow explain what's being observed?

**Comment by tsunamilx** [comment]
I thought the settings are automatically saved, no? I never do anything like force shutdown or anything, it is always normal restart.
The thing is that I never had this issue on weekdays, the issue is only on weekends.

It happened again last weekend, and I noticed that the setting "Never lock Trade Workstation" is GONE, leaving the "Lock in X minutes of inactivity" the only option, I think this is how the setting is reset, including the "auto restart" being reset to "auto logoff" as "auto restart" is disabled when "Never lock Trade Workstation" is unavailable or disabled. 
And after a few hours, it appears again and I am able to enable the setting "Never lock Trade Workstation" again, this is certainly not friendly to an automated system.

I am trying to reach out to IB support, waiting for reply.

On IBC side, can IBC detect if the setting "Never lock Trade Workstation" exists or not? If yes, can we always enable this setting (including the "auto restart" setting) when it exists and this behavior can be toggled on/off in the config.ini?

**Comment by rlktradewright** [comment]
Yes, If 'Auto save settings' is checked in the TWS Lock and Exit configuration, TWS settings are saved automatically, but, as I said before,, only when you do a tidy TWS closedown (unless you specifically save them manually). They are not saved automatically at the time you make the change.

But anyway it certainly looks like my suggestion about unsaved settings was incorrect. You may have noticed that many people (including me) were hit by this issue yesterday: first thing yesterday morning, my 'Never lock Trader Workstation' setting had vanished on both my live |(10.37) and paper (10.40) TWS's. But it came back again later. So I think someone at IBKR did something silly and then realised the problem and put it right.

I don't know why IBKR can't seem to make up their minds about that they're trying to do here: this has been going on for well over a year now.

I don't like using IBC to fix IBKR's bugs. So although IBC could check the 'Never lock Trade Workstation' setting at startup (if it's there!), I'm rel;uctant to do this, but I am considering it. 

But do let us know how they respond to your request (if they do).
