### ISSUE TITLE
2FA with IOS device

### ISSUE THREAD

**Issue by helhadry** [IbcAlpha/IBC#265]
Hello, 

I want to automate the 2FA with IBC so the user can receive the alert on his device to authenticate the TWS on another machine.
I'm using SecondFactorDevice=IB Key ==> but I'm not receiving any alert on the IBKR mobile but only the code via sms.

What is missing here exactly please ? is there any missing configuration here ?

Thanks.

**Comment by rlktradewright** [comment]
Do you get the alert if you run TWS without using IBC?

It’s worth noting that IBC isn’t involved at all in getting the alert to your device. It doesn't get involved until the Second Factor Authentication dialog is closed (either through timeout or through acknowledging the alert).

So if you don’t get the alert when NOT using IBC  then there’s probably something wrong with your IBKR Mobile registration

If you DO get the alert when not using IBC, then please supply the IBC logfile (the whole file, please – attach it to your reply rather than quoting it).

**Comment by helhadry** [comment]
hello, thanks a lot for your quick response, the paper account
