### ISSUE TITLE
Checking for gateway jars

### ISSUE THREAD

**Issue by chapma26** [IbcAlpha/IBC#28]
Hi, I'm a bit confused as to why the jars for the gateway are being checked. It knows the entry point is TWS. I ended up running it fine by manually running ibcstart.sh and passing the variables but it seems like possibly the gateway flag is being set somewhere when I just use twsstart.sh. I've never needed to have the gateway installed before and I didn't see anything about it in the latest release notes. Please see output below.

Great work getting this running with the new login, though. Thank you!

Starting IBC version 3.7.0 on 2018-11-14 at 18:50:53

Operating system: Linux OT 4.4.0-1070-aws #80-Ubuntu SMP Thu Oct 4 13:56:07 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

Arguments:

TWS version = 964
Entry point = **ibcalpha.ibc.IbcTws**
--tws-path = /home/ubuntu/Jts
--tws-settings-path = /home/ubuntu/Jts
--ibc-path = /home/ubuntu/ot/ibc
--ibc-ini = /home/ubuntu/ot/ibc/config.ini
--mode = paper
--java-path = 
--user = ***
--pw = ***

=========================== An error has occurred =============================

Error: **TWS version 964 is not installed: can't find /home/ubuntu/Jts/ibgateway/964/jars**

**Comment by rlktradewright** [comment]
Both the install for TWS and the install for Gateway contain the same jars, though they are installed in different places, so either installation can run either application.

When it's trying to find the jars, it first checks the location for whichever app you're starting, and if there's nothing there it checks the location for the other app. It does this so that you don't have to install both if you sometime want to use TWS and sometimes Gateway.

If neither location contains anything, you get the 'not installed' error message, and it's slightly misinformative because it reports for the location it checked last.

So it's really just saying it can't find either a TWS or a Gateway installation for 964. I'll fix it at some point so it's clearer.

Were you actually intending to run it for 964? Perhaps you just haven't edited twsstart.sh to use 974?

**Comment by chapma26** [comment]
Hmm, no - I think the twsstart.sh file is ok. I'll put the contents I changed below

TWS_MAJOR_VRSN=964
IBC_INI=/home/ubuntu/ot/ibc/config.ini
TRADING_MODE=paper
IBC_PATH=/home/ubuntu/ot/ibc
TWS_PATH=/home/ubuntu/Jts
LOG_PATH=/home/ubuntu/ot/ibc/logs
TWSUSERID=***
TWSPASSWORD=***
JAVA_PATH=
HIDE=

I get the same error as last night.

But running the command -
`/home/ubuntu/ot/ibc/scripts/ibcstart.sh 974 --tws-path=/home/ubuntu/Jts --tws-settings-path=/home/ubuntu/Jts --ibc-path=/home/ubuntu/ot/ibc --ibc-ini=/home/ubuntu/ot/ibc/config.ini --mode=paper
`
works just fine. 

For version 3.6 I had the same problem and I manually removed the check for gateway flags and the problem went away. I did the same for 3.7 and had to resort to running the ibscstart.sh script directly. It's all good as it still works. Might just be something weird on my system. If you don't see anything glaring between the changes in twsstart.sh and the command line then go ahead and close the ticket. Thanks for your response!

Chance

**Comment by chapma26** [comment]
Oh shit - I just saw the 964 typo. Sorry to waste your time! Ignore this.

**Comment by chapma26** [comment]
PS - This is what happens when you code personal projects at night after a long day of coding for your regular job.

**Comment by rlktradewright** [comment]
Oh, just wait till you get to  my age!...

Like last night, I put some butter in the frying pan for some eggs, and while it was melting I grated a load of cheese to eventually go on top of the eggs. Then I just dumped all the cheese straight into the frying pan... I do equivalent things while programming all the time - fortunately I usually manage to detect them before the code has melted entirely!
