### ISSUE TITLE
Prism ES2 Error - nInitialize: glXChooseFBConfig failed

### ISSUE THREAD

**Issue by ahanmal** [IbcAlpha/IBC#40]
Having trouble running IBC within a Docker container with gateway. I get the following error in the IBC log: `Prism ES2 Error - nInitialize: glXChooseFBConfig failed`.  Has anyone come across something similar? I believe it might be a Java issue; I'm using Oracle Java 8 on Ubuntu 16.04. Thanks!

**Comment by rlktradewright** [comment]
@ahanmal  Sorry for the delay in responding. I was hoping that someone else might have a handle on this but evidently not.

Could you please reply attaching your IBC logfile - it may contain something that might give a clue. Attach the whole thing, not just the bit you think is relevant. Since the log file for a particular day may contain the output from several runs, you can remove info from all except the last run.

It would also be helpful if you describe how you're constructing your container and getting the relevant files into it, or even attach your scripts.

And note that generally speaking it's best to use the 'private' Java that is installed with the Gateway. If you're installing the Gateway as part of your docker initialisation, this should be no problem, but if you're copying the files from elsewhere after the container has initialised you may need to do a bit more work.
