### ISSUE TITLE
user group

### ISSUE THREAD

**Issue by SteffenNa** [IbcAlpha/IBC#5]
Hello! Was wondering what happened to the user group as i wanted to access some information. The link on this repo leads to some book club and the IB Controller group is gone.
Could you please update the link or is there no user group anymore?
Thanks and regards
Steffen

**Comment by rlktradewright** [comment]
Oops, thanks for pointing that out! I've fixed the link now. It should have been [https://groups.io/g/ibcalpha](https://groups.io/g/ibcalpha)

The previous link was what I intended to be the new group's URL, but unfortunately someone else snatched it just before I did, and I forgot to update to the correct new link.

But I'm glad to see the Imperia Book Club is doing so well: two members and one topic! That's 0 additional members and 0 additional topics since they beat me to it.

**Comment by SteffenNa** [comment]
Beautiful part of the world that. Wouldn't mind sitting at the beach with a book in Imperia ;-)
I am about to set up a linux server with my shiny new trading framework coded in Python. Want to do that headless using IBC. Also using the amazing ib_insync which is a wrapper around the the IBKR python API and also wraps IBC. So i should be able to control everything from my python system. Thats why i was looking for the user group. First up i need to make sure IBC works. Will be in touch if i need help. Guess there have been discussions about headless Linux setup in the user group.
