### ISSUE TITLE
Timezone Issue

### ISSUE THREAD

**Issue by quantlearn** [IbcAlpha/IBC#60]
I am using IBC version 3.8.1 with TWS Build 972.1t, May 7, 2019, 10:25:42 AM on Ubuntu 18.04.

When I use TWS directly, I use the UTC timezone and then convert to local time as required in my own application.   I set the time zone to UTC in the Login window by selecting 'More Options' and configuring the time zone.  The time zone information is persisted so I only needed to configure the time zone once.   

When I invoke TWS from IBC, it loads successfully but the time zone is set from my machine local time.  I looked through the IBC configuration file and the user guide, but I have not found any information on how to fix this issue. 

I was wondering if anyone else has encountered this issue and whether there is a solution.

Many thanks,

Steven

**Comment by rlktradewright** [comment]
TWS takes its timezone setting from a file called Jts.ini (for example, TimeZone=Europe/London). I suspect that what’s happening here is that when you use IBC, a different Jts.ini file is referred to than when you run TWS manually, for example because you’ve configured IBC to store the TWS settings in a non-default location.

The easiest way to put this right is to blank out the password in your config.ini, and then run IBC: it will halt on the login dialog, with the username already entered but not the password (it’s important that the username is correct, because depending on various factors the Jts.ini file used might change when you do enter the username). Now set the timezone as desired, then enter the password and complete the login. Next time you run IBC, it should use your preferred timezone (don’t forget to put the password back into config.ini, obviously).

**Comment by quantlearn** [comment]
Thank you.  This issue is now resolved.

**Comment by atisharma** [comment]
To add for posterity, you can simply close IB Gateway, change the timezone in jts.ini, and restart the Gateway. The timezone for UTC is "Universal".
