### ISSUE TITLE
Permission denied: '/opt/ibc/scripts/ibcstart.sh'

### ISSUE THREAD

**Issue by joan-arau** [IbcAlpha/IBC#65]
Using Ibcontroller(from ib_insync) I am getting this error message:

PermissionError: [Errno 13] Permission denied: '/opt/ibc/scripts/ibcstart.sh'

I have done this in the terminal:

cd /opt/ibc
sudo chmod o+x *.sh /.sh

ls -l gives this:

-rw-r--r-x@ 1 USER staff 13606 4 Jun 12:37 ibcstart.sh

**Comment by shevkoplyas** [comment]
Joan,

instead of "o+x" do the "*u*+x"
explanation:
see man pages for chmod here <https://linux.die.net/man/1/chmod>, in
particular this quote:

*Instead of one or more of these letters, you can specify exactly one of
the letters ugo: the permissions granted to the user who owns the file (u),
the permissions granted to other users who are members of the file's group
(g), and the permissions granted to users that are in neither of the two
preceding categories (o).*
(end of quote)

You're doing it for "o" (which is "other") and I suggest to do for "u"
(which is "user") or you can make it "a+x" (which is all, so all can
execute)

cheers,
Dmitry Shevkoplyas
