### ISSUE TITLE
PasswordEncrypted is not available on new version?

### ISSUE THREAD

**Issue by oemGitHub** [IbcAlpha/IBC#7]
For config.ini, is PasswordEncrypted no longer support on latest IBCWin-3.6.0?
Since password is not encrypted under C:\Users\username\Documents\IBC, which IBC folder cannot be encrypted for window 7, but username folder is encrypted by default, would it be safe place for security?
Does anyone have any suggestions?
Thanks in advance for any suggestions

**Comment by rlktradewright** [comment]
`PasswordEncrypted` was not carried over from IBController to IBC, because in practice it was of no value. It really wasn't encryption, just a little shuffling, and anyone with half a brain could easily unencrypt it.

It appears that the Home editions of Windows don't offer folder or file encryption. To my mind, that alone is a good enough reason to move to the Pro edition.

There is no benefit in storing the config.ini file anywhere other than the recommended location. The personal folder at Users\<username> is secured against access by any other user. The only disadvantage with it not being encrypted is that someone who gains physical access to the computer can potentially run disk tools outside Windows that give access to the data, whereas if the file is encrypted this can never happen.
