### ISSUE TITLE
what's the relationship between this project and ib-controller?

### ISSUE THREAD

**Issue by abe-winter** [IbcAlpha/IBC#72]
Hi -- this project is very similar to https://github.com/ib-controller/ib-controller. Is one of these projects more maintained / considered primary? Why the duplication?

**Comment by rlktradewright** [comment]
The IBC project was forked from the original IBController project in March 2018. This resulted from an irreconcilable disagreement between me and the current owner of IBController.

As far as I'm aware, the original IBController project is now unmaintained, and I can see no valid reason why anyone would use it.

In contrast, IBC has moved on quite considerably since then.

**Comment by abe-winter** [comment]
oof

appreciate your work (on both projects), thanks for the info & I'll close this ticket
