### ISSUE TITLE
Where to download the latest IBC files?

### ISSUE THREAD

**Issue by oemGitHub** [IbcAlpha/IBC#73]
I would like to know on where to download the latest IBC files

I can only find 3.8.1 through following link
https://github.com/ibcalpha/ibc/releases/tag/3.8.1

Furthermore, IBC allows TWS to be shut down at a specified day of the week (again, this functionality no longer applies for TWS 974 or and later versions), which version of TWS should be downloaded?

I can only find TWS Offline 975 - 978, should I look for 972 or 973 in order to work properly with IBC 3.8.1?

IB API Latest for Windows Version : API 975 - 978
https://www.interactivebrokers.com/en/index.php?f=1657&ns=T&nhf=T

Does anyone have any suggestions?
Thanks in advance for any suggestions

**Comment by rlktradewright** [comment]
3.8.1 is the latest version.

You can no longer use IBC to keep TWS running for more than one day. This is due to a change IB made in TWS 974. There is absolutely nothing IBC can do about this.

If TWS 972 is no longer available, then you're clean out of luck. If you want to use IBC to automate the login, you have no choice but to restart TWS every day, using for example Task Scheduler on Windows or crontab on Linux.

Alternatively you can use the Auto-relogin functionality now built in to TWS, which will (in theory) keep TWS running all week. But you can't use this functionality if you use IBC to start TWS. 

My experience with the TWS Auto-relgoin has not been very successful, so I still use IBC. I set TWS to autologoff just before IB's daily reset time, and restart it using Task Scheduler just after it.

**Comment by oemGitHub** [comment]
At this moment, my old PC is using IBC 3.7.4 with TWS 974, which can login automatically and restart PC every 24 hours and scheduled to re-login again without problem.  

For new PC, do I need to install following package?
1) IBC 3.8.1
2) TWS Offline Installer 978

Would it be work fine to auto-login with scheduled task as well?

Do you have any suggestions?
Thank you very much for any suggestions (^v^)

**Comment by rlktradewright** [comment]
I repeat, you can no longer use IBC to keep TWS versions 974 or later running for several days. It simply doesn't work now, because IB have prevented it working. Nothing can be done to change this.

It if IS working for you with TWS 974, that will be because you're using an early version of 974 which didn't include the changes IB made.

So if you want to use this functionality, you should use TWS 972, which is still available for download from IB's website, provided you don't need to use any of the TWS features introduced in more recent versions. TWS 972 will still work fine with IBC 3.8.1.

If you do need to use a later version of TWS than 972, then yes you can simply restart IBC 3.8.1 using Task Scheduler every day, and it will automatically log you in.

**Comment by oemGitHub** [comment]
Referring to IB, the TWS Offline only offer Latest not stable version, I would like to know on whether IBC 3.8.1 can work with latest version as well except for stable version? 
Furthermore, for windows 10, I would like to know on which version Latest (32-bit) or Latest (64-bit) should work well with IBC 3.8.1.

Do you have any suggestions?
Thank you very much for any suggestions (^v^)

TWS Offline Installer
https://www.interactivebrokers.com/en/index.php?f=15875

**Comment by rlktradewright** [comment]
Well I don't know how you found that page on IB's website - I've never seen it before.

Here's how I find the TWS installers on the IB website: on the Technology menu, click TWS Software. Scroll right down to the bottom of the page that appears. There you'll see the Offline Installer for TWS 972.1v (as well as other installers).

So TWS 972 _is_ still available.

If you have a 64-bit operating system, you might as well use the 64-bit installer (though the page I pointed you to only offers me 64-bit, but that might be because it's detected that my OS is 64-bit). But I doubt it makes the slightest difference really. Of course if you have 32-bit Windows 10, then you must use a 32-bit installer.

IBC 3.8.1 works fine with any current version of TWS. It makes no difference at all whether its stable or latest.
