### ISSUE TITLE
enter security code via command server?

### ISSUE THREAD

**Issue by abe-winter** [IbcAlpha/IBC#74]
Is there any interest in having the ability to enter the security code via command server? My goal here is to be able to keep 2FA enabled on my account but still run headless in docker.

I'm open to doing this work and submitting a PR, let me know.

**Comment by rlktradewright** [comment]
That's an interesting suggestion, but I'd need to think about it a bit more to feel comfortable with it.

In any case, it may not be necessary. I have an update to IBC waiting to be released that should solve the problem. 

The way this works is that when TWS displays the 2FA window during authentication, and provided you have the IB Mobile app installed on your Android or IOS phone, then you'll be prompted on the phone, and when you respond IB will complete the TWS login.

I'm a bit ashamed to have to admit that I did this work months ago, and I believe one person has been using it successfully (at least I haven't heard otherwise),. but I've just never got round to releasing it. I will try to do this very soon, and will be very interested to know if it meets your needs.

**Comment by abe-winter** [comment]
Thanks! I'll close this issue for now and wait for your change

Let me also say thanks & that the IBC project is amazing -- I would be switching brokerages if this didn't exist.
