### ISSUE TITLE
Not handled WARNING dialog in paper-trade

### ISSUE THREAD

**Issue by AfroMetal** [IbcAlpha/IBC#8]
IB Gateway logs:
```
2018-05-24 22:00:03.719 [BW] INFO  [AWT-EventQueue-0] - Parent for Dialog does not implement IToFrontAsGroupWindow, isAlwaysOnTop: false parent: ibgateway.ao[frame1,162,109,700x550,invalid,layout=java.awt.BorderLayout,title=IB Gateway.  API Account: stef4810,resizable,normal,defaultCloseOperation=HIDE_ON_CLOSE,rootPane=javax.swing.JRootPane[,0,0,700x550,layout=jtscomponents.plaf.ae,alignmentX=0.0,alignmentY=0.0,border=,flags=16777673,maximumSize=,minimumSize=,preferredSize=],rootPaneCheckingEnabled=true]
2018-05-24 22:00:03.719 [BW] INFO  [AWT-EventQueue-0] - Parent for Dialog is not isAlwaysOnTop: ibgateway.ao[frame1,162,109,700x550,invalid,layout=java.awt.BorderLayout,title=IB Gateway.  API Account: stef4810,resizable,normal,defaultCloseOperation=HIDE_ON_CLOSE,rootPane=javax.swing.JRootPane[,0,0,700x550,layout=jtscomponents.plaf.ae,alignmentX=0.0,alignmentY=0.0,border=,flags=16777673,maximumSize=,minimumSize=,preferredSize=],rootPaneCheckingEnabled=true]
```
The pop-up dialog that shows up and does not get handled automatically.:
![popup](https://user-images.githubusercontent.com/9338199/40530441-1b813dec-5ff9-11e8-97d7-15c466ecbf24.png)

I have accepted it manually, but on each new order it keeps reappearing. Can't use the IB Gateway in headless mode with that.

**IBC:** 3.6.0
**IB Gateway:** 963, 969, 972 -  all behave the same
**IBApi:** 9.73.6

**Comment by rlktradewright** [comment]
I've never seen this dialog before. Please state which version of the Gateway you're using.

The message seems to indicate that you're trying to place orders outside regular trading hours without setting the relevant attribute on the order. Please confirm whether this is the case. And if it is the case, is your intention that the order will not be processed until the next market open?

**Comment by AfroMetal** [comment]
@rlktradewright just added the versions to first post.

I am not placing them outside trading hours. Orders are Forex and Gold/Silver placed few seconds after market open, also manual placing during the day displays the same dialog.

**Comment by AfroMetal** [comment]
@rlktradewright Problem is that when it is dismissed for one Order, then following pass through. But on IB Gateway restart the information that I've accepted the dialog is not preserved and it shows up again.

Am I doing something wrong regarding settings saving maybe? Or stuff like that does not sit in the settings file.

**Comment by rlktradewright** [comment]
The version numbers you've given are incorrect. Please correct them. I presume you mean 963, 969 and 972?

When did this start happening? Were you previously running successfully without it happening?

By the way, I think the statement in the dialog should probably say '_is NOT checked_' rather than '_is NOW checked_': it makes more sense to me that way.

The question is why this isn't happening for eveyone using the gateway? I'm just installing 972 and will switch my paper account over to the Gateway to see if all's well.

**Comment by AfroMetal** [comment]
@rlktradewright You are right, I've updated the versions.

> When did this start happening? Were you previously running successfully without it happening?

It was working without problems on that account for over a month. Problems with that dialog were found this Monday (21 May) but probably happening last week also but diagnosed only this week.

**Comment by rlktradewright** [comment]
Well, I'm baffled. I've tried my paper trading account with Gateway 972 and it's fine. A couple of points:

1.  Can you please check the trading hours in the contract details for the relevant contracts (or tell me exactly what contracts you're using if you don't happen to have a convenient means of doing this without programming). It may be that IBKR's view of the trading hours is not what you're expecting, so that this is in fact a valid message.

2. IBC could of course be enhanced to handle this dialog, but before doing so I'd like to be sure that we understand what's going on here. It could be that this is actually a bug in Gateway, and IBKR should fix it.

3. It's really irritating that IBKR insist on displaying these 'informational' pop-ups from the Gateway. I think it would be worth raising an enhancement request that Gateway should never pop-up anything (except the login dialog).

**Comment by AfroMetal** [comment]
@rlktradewright Contract trading hours should not be a problem, earlier orders placed outside of trading hours just got cancelled (rejected). That is some dialog related to account, but the problem is I have not changed any account's setting.

I guess the 'accept' button is the left one, so maybe it would be a good idea for IBC to log the dialog info to some file and then automatically press the left button no matter what dialog it is.

**Comment by rlktradewright** [comment]
Maybe your computer clock is not well enough synchronised, and what you think is 5 seconds after the open is actually just before?

Also you could try setting the ignoreRTH to true and see if it then works.

Maybe I'm clutching at straws here, but the fact is that this problem seems only to affect you, and it's really quite unlikely that the Gateway would issue such a message erroneously, especially if it was working fine before. In other words, there is some condition here that you need to get to the bottom of. Putting a kludge fix into IBC is not the right solution. If you're absolutely sure the message is incorrect, you should probably contact IBKR to find out what's causing it.

**Comment by AfroMetal** [comment]
The solution proposed by IB Support was to run IB Gateway manually, place order manually, then discard that popup properly and make sure that IB Gateway is shut down manually so that server can synchronize with it and save the settings. It may have been caused by killing the process instead of shutting down nicely. That way the IB Servers had no way to register the popup acceptance. 

What is strange to me is that from what they say the popup acceptance is only registered on logout and not when it is actually done.
