### ISSUE TITLE
BindAddress does not seem to work.

### ISSUE THREAD

**Issue by ngyangjo** [IbcAlpha/IBC#85]
TrustedIP value is always set to 127.0.01 in IBGateway regardless of what I set in BindAddress.
It's happening for both macos and Linux script.

**Comment by rlktradewright** [comment]
`BindAddress` in `config.ini` has absolutely nothing whatever to do with the Gateway.

That's why there is this comment a few lines above in `config.ini`:

```
# Do NOT CHANGE THE FOLLOWING SETTINGS unless you
# intend to issue commands to IBC (for example
# using telnet). Note that these settings have nothing to
# do with running programs that use the TWS API.

```

You only use this setting if you need to send commands (eg `STOP`) to IBC, and, as the comment for `BindAddress` says, you'd only need to use it then if you have a multi-homed host (ie more than one network adapter) but you don't want command server connections to be accepted on all of them. 

So what exactly are you really trying to do?

**Comment by ngyangjo** [comment]
Hmm. I thought that comment applied to only point 6. But Im trying to change the value of "Trusted Ips" in IBGateway, so I can connect to IBGateway from another server too. It by default only allows localhost connection.

![Screen Shot 2020-04-12 at 9 08 25 PM](https://user-images.githubusercontent.com/5336038/79072638-d62e0180-7d01-11ea-8b1e-a95c67cdd49a.png)

I want to change it allow other machines IP so I can connect it remotely too.

I believe, before in IBController, an attribute name IbBindAddress made it possible, didn't it? And the IBC User guide says that the IbBindAddress equivalent is BindAddress in IBC.

**Comment by rlktradewright** [comment]
No, neither IBC nor IBController have ever allowed you to set the trusted IP addresses. The only way to set them is via the Global Configuration dialog in the Gateway/TWS (as per your screenshot).

'`BindAddress` is one of the several settings within point 6, and the comment applies to all of them.

**Comment by ngyangjo** [comment]
Hmm, I see. I must have misread it then.
