### ISSUE TITLE
Keeping user/pass in config.ini is not universal

### ISSUE THREAD

**Issue by zdytch** [IbcAlpha/IBC#88]
1. It is necessary to keep config.ini under GIT, because it stores crucial configuration, e.g. when deploying Docker container
2. It is insecure to keep login/pass under GIT
3. Either split config.ini to store login/pass separately, or allow using environment variables in config.ini, e.g:
IbLoginId=${IB_LOGIN}
IbPassword=${IB_PASSWORD}

**Comment by rlktradewright** [comment]
When you build your Docker image, you need to ensure that the image contains a copy of config.ini that you have customised to your needs, particularly the userid and password.

So create a copy of config.ini in the Docker build context, edit it as desired, and use a Docker COPY command to put config.ini into the correct place.

Doing it this way, you won't need to edit the config.ini in the repo, and you can secure the config.ini that you COPY from the build context in whatever way seems best to you.

By the way, the same is true of the script for starting IBC: you may well want to change it from what is in the repo, especially the TWS/Gateway major version number, so use a similar technique for that.

**Comment by zdytch** [comment]
For sure I can do (and actually do) this way. But better approaches exist, not to spread sensitive and variable data through different files. Besides storing sensitive login/pass data, various scenarios may exist: 
- live/paper for production/development
- new/old TWS versions for production/development
- etc

So it's hard to maintain, especially for big projects.

An approach is to use Docker environment files (.ENV) which collect all the variables (sensitive and versions/paths/etc as well). Then various config files need to get that variables. But from IBC .ini I cannot access them (it's not documented and I wasn't able get any success whet I try).

Another approach is to use Docker Secrets or GitHub Secrets. I never used them yet, but guess it also won't work with hard-coded .ini file.

**Comment by rlktradewright** [comment]
I'm afraid I'm completely at a loss to see the problem here. 

I run multiple installations for live, paper demo (no longer available now), and have no trouble maintaining it. You just set each one up once, and then you can forget about it. It's perfectly secure because the config.ini files are stored in folders private to the user under which it runs. The config.ini files are also encrypted, so even if someone steals my server they wouldn't be able to see the contents of the config.ini files with low-level disk utilities.

Remember also that the vast majority of users run IBC as a normal process in a 'normal' machine (ie physical or virtual, not in a container).  So I definitely don't want IBC to contain anything that is specific to use of Docker.

I don't even know what you mean when you refer to 'big projects'. Maybe you need to say more about your use case? For example if you're in a scenario where you want to run many instances of IBC, for example one per customer in its own container, then I can imagine you'd need to do some fancy things to manage it, but those fancy things do not need to be part of IBC itself. If there is some enhancement to IBC that would make it more easily support such a scenario, I would give it due consideration, but things like splitting out parts of config.ini or incorporating an environment variable expansion capability into config.ini are simply not going to happen.

And if need be you can write your own Settings Manager, Login Manager, MainWindow manager and TradingMode Manager to override the built-in ones and inject them into IBC. There is a simple example of this in the samples/ibcloader directory in the repo.
