### ISSUE TITLE
why no TWS GUI when I run IBController.bat using windows scheduler?

### ISSUE THREAD

**Issue by memoryfraction** [IbcAlpha/IBC#9]
I import "Start TWS Live(daily).xml" to windows scheduler. Then I found no GUI appears, but a backend java.exe process is initiated as below pics; and I can communicate with the process using my application.
If I choose to start "IBControllerStart.bat" by double click manually. GUI does appear;

Can I know why GUI does not appear when initiated by windows scheduler?
![image](https://user-images.githubusercontent.com/18358791/40632186-388e501c-62b2-11e8-91a2-6fdf8b6f1410.png)

**Comment by rlktradewright** [comment]
First of all, this is the IBC repository, but you seem to be running IBController, rather than IBC. So please if you want to be supported on this repository, switch to IBC.

For the GUI to be visible, the computer MUST be logged in to the user that the scheduled task runs under before the task starts. 

If the relevant user is not logged in, Windows starts the scheduled task with its own user session; if the user then logs in later, there is now way for that original session to share the desktop.

**Comment by memoryfraction** [comment]
Thanks for reply.
 I already switched to IBC instead of IBController just now;
I still get a backend process without GUI even if I click "Run" button in windows scheduler.  Log in user is the same the user of scheduled task;
Any other advice?
![image](https://user-images.githubusercontent.com/18358791/40627100-e1bf9768-628a-11e8-9731-5d65dca8d1bb.png)
 
![image](https://user-images.githubusercontent.com/18358791/40627163-6558818e-628b-11e8-8a4c-d9773d471497.png)

**Comment by memoryfraction** [comment]
And scheduler user and log on user is the same one.
![image](https://user-images.githubusercontent.com/18358791/40631760-86a1f164-62ad-11e8-8653-0b70ac2223d0.png)

**Comment by rlktradewright** [comment]
But you have checked the option for 'Run whether user is logged on or not'.

You need to check 'Run only when user is logged on'.

If you show the 'Session ID' column in Task Manager you'll be able to see instantly whether IBC is running in the user session. 

By the way, I don't recommend running IBC (or any other user program) under the Adminstrator user. It's not necessary. Use a 'normal' non-privileged account.

**Comment by memoryfraction** [comment]
Thanks for your help , IBC and TWS is visible on my server now.
