### ISSUE TITLE
Minimize window stopped working

### ISSUE THREAD

**Issue by lihanchen** [IbcAlpha/IBC#92]
The minimize window feature used to work before When used IBC of a few months old + TWS 979.4.
Now after updated to latest IBC + TWS 979.5a it stopped working.
I am running it on Linux Mint.
After TWS starts up as a mid sized window, I can see it gets minimized. Then after about 0.5 seconds, It get maximized instead.
Maybe IBC minimized it too early.

**Comment by rlktradewright** [comment]
It's working fine for me on TWS 979.5b. This is on Windows, but it should behave exactly the same on both Windows and Linux as the jar files are the same. I won't be able to try it on Linux until late tomorrow evening.

I believe a recent version of TWS 979.4 (possibly .4z) introduced a new dialog that is displayed at startup. This is one of those dialogs that has a 'don't show this again' checkbox, and IBC never handles them because the user can manually configure this behaviour. It may well be that this dialog is interfering with the minimizing functionality, if you haven't told it not to show itself in future. Let me know if this dialog is displaying. If you want it to be shown, you probably won't be able to use the minimise option.

You could also try installing TWS 979.5b and see if that makes any difference.

If you can't get it to work, then attach your IBC logfile to your reply (don't quote it inline). By the way, for future reference, whenever you create an issue here it's always worth giving full details of which IBC version you're using (attaching a log file is a good way of doing this).

**Comment by lihanchen** [comment]
Hi. Thanks for the quick response.
I tried 979.5b and it still didn't work.
The tws didn't get minimized at all this time. And there is no pop up.
Here is the log.
[ibc-3.8.3_TWS-979_Thursday.txt](https://github.com/IbcAlpha/IBC/files/5105740/ibc-3.8.3_TWS-979_Thursday.txt)

**Comment by rlktradewright** [comment]
Thanks for the logfile. It doesn't directly help, but I note that you're using your live account whereas I'm using my paper-trading account (my live account is on TWS 978). It's possible that may make a difference.

But there's nothing more I can do or suggest until I can run with my live account, and also do it on Linux, which as I said won't be till late tomorrow (Friday), or perhaps Saturday.

**Comment by lihanchen** [comment]
Hi. I tried again with my paper account that used to work before updating.
This time the paper account stopped working.
Also, IBC cannot click the "I understand" button in the "This is not a brokerage account" popup
[ibc-3.8.3_TWS-979_Wednesday.txt](https://github.com/IbcAlpha/IBC/files/5132559/ibc-3.8.3_TWS-979_Wednesday.txt)

**Comment by rlktradewright** [comment]
The paper-trading warning dialog is detected at 12:58:44:508.

If it's not handling it, the only possibility is that you don't have this setting in your config.ini:

`AcceptNonBrokerageAccountWarning=yes`

Note that setting names are cases-sensitive, so you have to spell it exactly right.

**Comment by lihanchen** [comment]
It's working again. The reason is unknown. I don't remember changing anything.
